// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type AuthProvider struct {
	Provider               string             `json:"provider"`
	DisplayName            string             `json:"display_name"`
	Enabled                bool               `json:"enabled"`
	ClientID               string             `json:"client_id"`
	ClientSecretCiphertext []byte             `json:"client_secret_ciphertext"`
	IssuerUrl              string             `json:"issuer_url"`
	AuthUrl                string             `json:"auth_url"`
	TokenUrl               string             `json:"token_url"`
	UserinfoUrl            string             `json:"userinfo_url"`
	Scopes                 string             `json:"scopes"`
	Metadata               []byte             `json:"metadata"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

type Build struct {
	ID           pgtype.UUID        `json:"id"`
	ProjectID    pgtype.UUID        `json:"project_id"`
	ServiceID    pgtype.UUID        `json:"service_id"`
	Status       string             `json:"status"`
	GithubCommit string             `json:"github_commit"`
	GithubBranch string             `json:"github_branch"`
	ImageID      pgtype.UUID        `json:"image_id"`
	VmID         pgtype.UUID        `json:"vm_id"`
	ProcessingBy pgtype.UUID        `json:"processing_by"`
	BuildingAt   pgtype.Timestamptz `json:"building_at"`
	FailedAt     pgtype.Timestamptz `json:"failed_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type BuildLog struct {
	ID        pgtype.UUID        `json:"id"`
	BuildID   pgtype.UUID        `json:"build_id"`
	Message   string             `json:"message"`
	Level     string             `json:"level"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type CertmagicDatum struct {
	Key      string             `json:"key"`
	Value    []byte             `json:"value"`
	Modified pgtype.Timestamptz `json:"modified"`
}

type CiJob struct {
	ID                     pgtype.UUID        `json:"id"`
	ProjectID              pgtype.UUID        `json:"project_id"`
	Status                 string             `json:"status"`
	Source                 string             `json:"source"`
	WorkflowName           string             `json:"workflow_name"`
	WorkflowFile           string             `json:"workflow_file"`
	SelectedJobID          string             `json:"selected_job_id"`
	EventName              string             `json:"event_name"`
	InputValues            []byte             `json:"input_values"`
	InputArchivePath       string             `json:"input_archive_path"`
	ProviderConnectionID   pgtype.UUID        `json:"provider_connection_id"`
	ExternalRepo           string             `json:"external_repo"`
	ExternalInstallationID int64              `json:"external_installation_id"`
	ExternalWorkflowJobID  int64              `json:"external_workflow_job_id"`
	ExternalWorkflowRunID  int64              `json:"external_workflow_run_id"`
	ExternalRunAttempt     int32              `json:"external_run_attempt"`
	ExternalHtmlUrl        string             `json:"external_html_url"`
	RunnerLabels           []byte             `json:"runner_labels"`
	RunnerName             string             `json:"runner_name"`
	RequireMicrovm         bool               `json:"require_microvm"`
	ExecutionBackend       string             `json:"execution_backend"`
	WorkspaceDir           string             `json:"workspace_dir"`
	ProcessingBy           pgtype.UUID        `json:"processing_by"`
	ExitCode               pgtype.Int4        `json:"exit_code"`
	ErrorMessage           string             `json:"error_message"`
	StartedAt              pgtype.Timestamptz `json:"started_at"`
	FinishedAt             pgtype.Timestamptz `json:"finished_at"`
	CanceledAt             pgtype.Timestamptz `json:"canceled_at"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

type CiJobArtifact struct {
	ID        pgtype.UUID        `json:"id"`
	CiJobID   pgtype.UUID        `json:"ci_job_id"`
	Name      string             `json:"name"`
	Path      string             `json:"path"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type CiJobLog struct {
	ID        pgtype.UUID        `json:"id"`
	CiJobID   pgtype.UUID        `json:"ci_job_id"`
	Message   string             `json:"message"`
	Level     string             `json:"level"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ClusterAuditEvent struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	Action       string             `json:"action"`
	ResourceType string             `json:"resource_type"`
	ResourceID   string             `json:"resource_id"`
	Details      []byte             `json:"details"`
	RequestIp    string             `json:"request_ip"`
	UserAgent    string             `json:"user_agent"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type ClusterSecret struct {
	Key        string             `json:"key"`
	Ciphertext []byte             `json:"ciphertext"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type ClusterSetting struct {
	Key       string             `json:"key"`
	Value     string             `json:"value"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Deployment struct {
	ID                       pgtype.UUID        `json:"id"`
	ProjectID                pgtype.UUID        `json:"project_id"`
	ServiceID                pgtype.UUID        `json:"service_id"`
	BuildID                  pgtype.UUID        `json:"build_id"`
	ImageID                  pgtype.UUID        `json:"image_id"`
	VmID                     pgtype.UUID        `json:"vm_id"`
	PromotedFromDeploymentID pgtype.UUID        `json:"promoted_from_deployment_id"`
	GithubCommit             string             `json:"github_commit"`
	GithubBranch             string             `json:"github_branch"`
	DeploymentKind           string             `json:"deployment_kind"`
	PreviewEnvironmentID     pgtype.UUID        `json:"preview_environment_id"`
	PreviewLastRequestAt     pgtype.Timestamptz `json:"preview_last_request_at"`
	PreviewScaledToZero      bool               `json:"preview_scaled_to_zero"`
	CircuitBroken            bool               `json:"circuit_broken"`
	RunningAt                pgtype.Timestamptz `json:"running_at"`
	StoppedAt                pgtype.Timestamptz `json:"stopped_at"`
	FailedAt                 pgtype.Timestamptz `json:"failed_at"`
	DeletedAt                pgtype.Timestamptz `json:"deleted_at"`
	WakeRequestedAt          pgtype.Timestamptz `json:"wake_requested_at"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
}

type DeploymentInstance struct {
	ID                    pgtype.UUID        `json:"id"`
	DeploymentID          pgtype.UUID        `json:"deployment_id"`
	ServerID              pgtype.UUID        `json:"server_id"`
	VmID                  pgtype.UUID        `json:"vm_id"`
	Role                  string             `json:"role"`
	CloneSourceInstanceID pgtype.UUID        `json:"clone_source_instance_id"`
	Status                string             `json:"status"`
	RestartCount          int32              `json:"restart_count"`
	LastRestartAt         pgtype.Timestamptz `json:"last_restart_at"`
	DeletedAt             pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type Domain struct {
	ID                   pgtype.UUID        `json:"id"`
	ProjectID            pgtype.UUID        `json:"project_id"`
	ServiceID            pgtype.UUID        `json:"service_id"`
	DeploymentID         pgtype.UUID        `json:"deployment_id"`
	DomainName           string             `json:"domain_name"`
	VerificationToken    string             `json:"verification_token"`
	VerifiedAt           pgtype.Timestamptz `json:"verified_at"`
	RedirectTo           pgtype.Text        `json:"redirect_to"`
	RedirectStatusCode   pgtype.Int4        `json:"redirect_status_code"`
	DomainKind           string             `json:"domain_kind"`
	PreviewEnvironmentID pgtype.UUID        `json:"preview_environment_id"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type EnvironmentVariable struct {
	ID        pgtype.UUID        `json:"id"`
	ProjectID pgtype.UUID        `json:"project_id"`
	ServiceID pgtype.UUID        `json:"service_id"`
	Name      string             `json:"name"`
	Value     string             `json:"value"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Image struct {
	ID         pgtype.UUID        `json:"id"`
	Registry   string             `json:"registry"`
	Repository string             `json:"repository"`
	Tag        string             `json:"tag"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type InstanceMigration struct {
	ID                    pgtype.UUID        `json:"id"`
	DeploymentInstanceID  pgtype.UUID        `json:"deployment_instance_id"`
	SourceServerID        pgtype.UUID        `json:"source_server_id"`
	DestinationServerID   pgtype.UUID        `json:"destination_server_id"`
	SourceVmID            pgtype.UUID        `json:"source_vm_id"`
	State                 string             `json:"state"`
	Mode                  string             `json:"mode"`
	ReceiveAddr           string             `json:"receive_addr"`
	ReceiveTokenHash      []byte             `json:"receive_token_hash"`
	DestinationRuntimeUrl string             `json:"destination_runtime_url"`
	FailureCode           string             `json:"failure_code"`
	FailureMessage        string             `json:"failure_message"`
	CutoverDeadlineAt     pgtype.Timestamptz `json:"cutover_deadline_at"`
	StartedAt             pgtype.Timestamptz `json:"started_at"`
	CompletedAt           pgtype.Timestamptz `json:"completed_at"`
	FailedAt              pgtype.Timestamptz `json:"failed_at"`
	AbortedAt             pgtype.Timestamptz `json:"aborted_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type InstanceUsageSample struct {
	ID                   pgtype.UUID        `json:"id"`
	ServerID             pgtype.UUID        `json:"server_id"`
	ProjectID            pgtype.UUID        `json:"project_id"`
	DeploymentID         pgtype.UUID        `json:"deployment_id"`
	DeploymentInstanceID pgtype.UUID        `json:"deployment_instance_id"`
	SampledAt            pgtype.Timestamptz `json:"sampled_at"`
	CpuNanosCumulative   int64              `json:"cpu_nanos_cumulative"`
	CpuPercent           pgtype.Float8      `json:"cpu_percent"`
	MemoryRssBytes       int64              `json:"memory_rss_bytes"`
	DiskReadBytes        int64              `json:"disk_read_bytes"`
	DiskWriteBytes       int64              `json:"disk_write_bytes"`
	Source               string             `json:"source"`
}

type OrgNetwork struct {
	OrganizationID pgtype.UUID        `json:"organization_id"`
	Cidr           netip.Prefix       `json:"cidr"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type OrgOnboarding struct {
	OrganizationID pgtype.UUID        `json:"organization_id"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
	WizardState    []byte             `json:"wizard_state"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type OrgProviderConnection struct {
	ID                    pgtype.UUID        `json:"id"`
	OrganizationID        pgtype.UUID        `json:"organization_id"`
	Provider              string             `json:"provider"`
	ExternalSlug          string             `json:"external_slug"`
	DisplayLabel          string             `json:"display_label"`
	CredentialsCiphertext []byte             `json:"credentials_ciphertext"`
	Metadata              []byte             `json:"metadata"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type Organization struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Slug        string             `json:"slug"`
	EmailDomain string             `json:"email_domain"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type OrganizationMembership struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	UserID         pgtype.UUID        `json:"user_id"`
	Role           string             `json:"role"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type PreviewEnvironment struct {
	ID                 pgtype.UUID        `json:"id"`
	ProjectID          pgtype.UUID        `json:"project_id"`
	ServiceID          pgtype.UUID        `json:"service_id"`
	Provider           string             `json:"provider"`
	PrNumber           int32              `json:"pr_number"`
	HeadBranch         string             `json:"head_branch"`
	HeadSha            string             `json:"head_sha"`
	LatestDeploymentID pgtype.UUID        `json:"latest_deployment_id"`
	StableDomainName   string             `json:"stable_domain_name"`
	ClosedAt           pgtype.Timestamptz `json:"closed_at"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type Project struct {
	ID                     pgtype.UUID        `json:"id"`
	OrgID                  pgtype.UUID        `json:"org_id"`
	Name                   string             `json:"name"`
	GithubRepository       string             `json:"github_repository"`
	GithubInstallationID   int64              `json:"github_installation_id"`
	GithubWebhookSecret    string             `json:"github_webhook_secret"`
	RootDirectory          string             `json:"root_directory"`
	DockerfilePath         string             `json:"dockerfile_path"`
	DesiredInstanceCount   int32              `json:"desired_instance_count"`
	MinInstanceCount       int32              `json:"min_instance_count"`
	MaxInstanceCount       int32              `json:"max_instance_count"`
	LastRequestAt          pgtype.Timestamptz `json:"last_request_at"`
	ScaledToZero           bool               `json:"scaled_to_zero"`
	ScaleToZeroEnabled     bool               `json:"scale_to_zero_enabled"`
	BuildOnlyOnRootChanges bool               `json:"build_only_on_root_changes"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

type ProjectHttpUsageRollup struct {
	ID           pgtype.UUID        `json:"id"`
	ServerID     pgtype.UUID        `json:"server_id"`
	ProjectID    pgtype.UUID        `json:"project_id"`
	DeploymentID pgtype.UUID        `json:"deployment_id"`
	BucketStart  pgtype.Timestamptz `json:"bucket_start"`
	RequestCount int64              `json:"request_count"`
	Status2xx    int64              `json:"status_2xx"`
	Status4xx    int64              `json:"status_4xx"`
	Status5xx    int64              `json:"status_5xx"`
	BytesIn      int64              `json:"bytes_in"`
	BytesOut     int64              `json:"bytes_out"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type ProjectVolume struct {
	ID                     pgtype.UUID        `json:"id"`
	ProjectID              pgtype.UUID        `json:"project_id"`
	ServiceID              pgtype.UUID        `json:"service_id"`
	ServerID               pgtype.UUID        `json:"server_id"`
	AttachedVmID           pgtype.UUID        `json:"attached_vm_id"`
	MountPath              string             `json:"mount_path"`
	SizeGb                 int32              `json:"size_gb"`
	Filesystem             string             `json:"filesystem"`
	Status                 string             `json:"status"`
	Health                 string             `json:"health"`
	BackupSchedule         string             `json:"backup_schedule"`
	BackupRetentionCount   int32              `json:"backup_retention_count"`
	PreDeleteBackupEnabled bool               `json:"pre_delete_backup_enabled"`
	LastError              string             `json:"last_error"`
	DeletedAt              pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

type ProjectVolumeBackup struct {
	ID              pgtype.UUID        `json:"id"`
	ProjectVolumeID pgtype.UUID        `json:"project_volume_id"`
	Kind            string             `json:"kind"`
	StorageUrl      string             `json:"storage_url"`
	StorageKey      string             `json:"storage_key"`
	SizeBytes       int64              `json:"size_bytes"`
	Status          string             `json:"status"`
	Error           string             `json:"error"`
	Metadata        []byte             `json:"metadata"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
	FailedAt        pgtype.Timestamptz `json:"failed_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type ProjectVolumeOperation struct {
	ID              pgtype.UUID        `json:"id"`
	ProjectVolumeID pgtype.UUID        `json:"project_volume_id"`
	ServerID        pgtype.UUID        `json:"server_id"`
	Kind            string             `json:"kind"`
	Status          string             `json:"status"`
	RequestMetadata []byte             `json:"request_metadata"`
	ResultMetadata  []byte             `json:"result_metadata"`
	Error           string             `json:"error"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
	FailedAt        pgtype.Timestamptz `json:"failed_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type RemoteVm struct {
	ID                 pgtype.UUID        `json:"id"`
	OrgID              pgtype.UUID        `json:"org_id"`
	Name               string             `json:"name"`
	HostGroup          string             `json:"host_group"`
	IsolationPolicy    string             `json:"isolation_policy"`
	Backend            string             `json:"backend"`
	Arch               string             `json:"arch"`
	DesiredState       string             `json:"desired_state"`
	ObservedState      string             `json:"observed_state"`
	ServerID           pgtype.UUID        `json:"server_id"`
	VmID               pgtype.UUID        `json:"vm_id"`
	TemplateID         pgtype.UUID        `json:"template_id"`
	BaseImageRef       string             `json:"base_image_ref"`
	Vcpu               int32              `json:"vcpu"`
	MemoryMb           int32              `json:"memory_mb"`
	DiskGb             int32              `json:"disk_gb"`
	EnvJson            []byte             `json:"env_json"`
	GitRepo            string             `json:"git_repo"`
	GitRef             string             `json:"git_ref"`
	AutoSuspendSeconds int64              `json:"auto_suspend_seconds"`
	LastUsedAt         pgtype.Timestamptz `json:"last_used_at"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
	PublishedHttpPort  pgtype.Int4        `json:"published_http_port"`
	RuntimeUrl         string             `json:"runtime_url"`
	SshHostPublicKey   string             `json:"ssh_host_public_key"`
	FailureMessage     string             `json:"failure_message"`
	CreatedByUserID    pgtype.UUID        `json:"created_by_user_id"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type RemoteVmAccessEvent struct {
	ID           pgtype.UUID        `json:"id"`
	RemoteVmID   pgtype.UUID        `json:"remote_vm_id"`
	UserID       pgtype.UUID        `json:"user_id"`
	AccessMethod string             `json:"access_method"`
	EventType    string             `json:"event_type"`
	ExitCode     pgtype.Int4        `json:"exit_code"`
	ErrorSummary string             `json:"error_summary"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type RemoteVmPublishedPort struct {
	ID             pgtype.UUID        `json:"id"`
	RemoteVmID     pgtype.UUID        `json:"remote_vm_id"`
	TargetPort     int32              `json:"target_port"`
	Protocol       string             `json:"protocol"`
	Visibility     string             `json:"visibility"`
	PublicHostname string             `json:"public_hostname"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type RemoteVmTemplate struct {
	ID               pgtype.UUID        `json:"id"`
	OrgID            pgtype.UUID        `json:"org_id"`
	Name             string             `json:"name"`
	HostGroup        string             `json:"host_group"`
	IsolationPolicy  string             `json:"isolation_policy"`
	Backend          string             `json:"backend"`
	Arch             string             `json:"arch"`
	SourceRemoteVmID pgtype.UUID        `json:"source_remote_vm_id"`
	ServerID         pgtype.UUID        `json:"server_id"`
	BaseImageRef     string             `json:"base_image_ref"`
	SnapshotRef      string             `json:"snapshot_ref"`
	Vcpu             int32              `json:"vcpu"`
	MemoryMb         int32              `json:"memory_mb"`
	DiskGb           int32              `json:"disk_gb"`
	Status           string             `json:"status"`
	FailureMessage   string             `json:"failure_message"`
	CreatedByUserID  pgtype.UUID        `json:"created_by_user_id"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type Server struct {
	ID                 pgtype.UUID        `json:"id"`
	Hostname           string             `json:"hostname"`
	InternalIp         string             `json:"internal_ip"`
	IpRange            netip.Prefix       `json:"ip_range"`
	WireguardIp        netip.Addr         `json:"wireguard_ip"`
	WireguardPublicKey string             `json:"wireguard_public_key"`
	WireguardEndpoint  string             `json:"wireguard_endpoint"`
	Status             string             `json:"status"`
	LastHeartbeatAt    pgtype.Timestamptz `json:"last_heartbeat_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type ServerComponentStatus struct {
	ServerID         pgtype.UUID        `json:"server_id"`
	Component        string             `json:"component"`
	Status           string             `json:"status"`
	ObservedAt       pgtype.Timestamptz `json:"observed_at"`
	LastSuccessAt    pgtype.Timestamptz `json:"last_success_at"`
	LastErrorAt      pgtype.Timestamptz `json:"last_error_at"`
	LastErrorMessage string             `json:"last_error_message"`
	Metadata         []byte             `json:"metadata"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type ServerSetting struct {
	ServerID                     pgtype.UUID        `json:"server_id"`
	RuntimeOverride              string             `json:"runtime_override"`
	AdvertiseHost                string             `json:"advertise_host"`
	InternalApiPort              int32              `json:"internal_api_port"`
	CloudHypervisorBin           string             `json:"cloud_hypervisor_bin"`
	CloudHypervisorKernelPath    string             `json:"cloud_hypervisor_kernel_path"`
	CloudHypervisorInitramfsPath string             `json:"cloud_hypervisor_initramfs_path"`
	CloudHypervisorStateDir      string             `json:"cloud_hypervisor_state_dir"`
	UpdatedAt                    pgtype.Timestamptz `json:"updated_at"`
}

type Service struct {
	ID                     pgtype.UUID        `json:"id"`
	ProjectID              pgtype.UUID        `json:"project_id"`
	Name                   string             `json:"name"`
	Slug                   string             `json:"slug"`
	RootDirectory          string             `json:"root_directory"`
	DockerfilePath         string             `json:"dockerfile_path"`
	DesiredInstanceCount   int32              `json:"desired_instance_count"`
	BuildOnlyOnRootChanges bool               `json:"build_only_on_root_changes"`
	PublicDefault          bool               `json:"public_default"`
	IsPrimary              bool               `json:"is_primary"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

type ServiceEndpoint struct {
	ID              pgtype.UUID        `json:"id"`
	ServiceID       pgtype.UUID        `json:"service_id"`
	Name            string             `json:"name"`
	Protocol        string             `json:"protocol"`
	TargetPort      int32              `json:"target_port"`
	Visibility      string             `json:"visibility"`
	PrivateIp       netip.Addr         `json:"private_ip"`
	PublicHostname  string             `json:"public_hostname"`
	LastHealthyAt   pgtype.Timestamptz `json:"last_healthy_at"`
	LastUnhealthyAt pgtype.Timestamptz `json:"last_unhealthy_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Team struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	Name           string             `json:"name"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type TeamMembership struct {
	TeamID    pgtype.UUID        `json:"team_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID              pgtype.UUID        `json:"id"`
	Email           string             `json:"email"`
	PasswordHash    string             `json:"password_hash"`
	DisplayName     string             `json:"display_name"`
	IsPlatformAdmin bool               `json:"is_platform_admin"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type UserApiKey struct {
	ID             pgtype.UUID        `json:"id"`
	UserID         pgtype.UUID        `json:"user_id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	Name           string             `json:"name"`
	TokenHash      []byte             `json:"token_hash"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	LastUsedAt     pgtype.Timestamptz `json:"last_used_at"`
	RevokedAt      pgtype.Timestamptz `json:"revoked_at"`
}

type UserIdentity struct {
	ID                  pgtype.UUID        `json:"id"`
	UserID              pgtype.UUID        `json:"user_id"`
	Provider            string             `json:"provider"`
	ProviderSubject     string             `json:"provider_subject"`
	ProviderLogin       string             `json:"provider_login"`
	ProviderEmail       string             `json:"provider_email"`
	ProviderDisplayName string             `json:"provider_display_name"`
	Claims              []byte             `json:"claims"`
	LastLoginAt         pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type UserSession struct {
	ID                    pgtype.UUID        `json:"id"`
	UserID                pgtype.UUID        `json:"user_id"`
	TokenHash             []byte             `json:"token_hash"`
	CurrentOrganizationID pgtype.UUID        `json:"current_organization_id"`
	ExpiresAt             pgtype.Timestamptz `json:"expires_at"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
}

type UserSshKey struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Name      string             `json:"name"`
	PublicKey string             `json:"public_key"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Vm struct {
	ID              pgtype.UUID        `json:"id"`
	ServerID        pgtype.UUID        `json:"server_id"`
	ImageID         pgtype.UUID        `json:"image_id"`
	Status          string             `json:"status"`
	Runtime         string             `json:"runtime"`
	SnapshotRef     pgtype.Text        `json:"snapshot_ref"`
	SharedRootfsRef string             `json:"shared_rootfs_ref"`
	CloneSourceVmID pgtype.UUID        `json:"clone_source_vm_id"`
	Vcpus           int32              `json:"vcpus"`
	Memory          int32              `json:"memory"`
	IpAddress       netip.Addr         `json:"ip_address"`
	Port            pgtype.Int4        `json:"port"`
	EnvVariables    pgtype.Text        `json:"env_variables"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type VmLog struct {
	ID        pgtype.UUID        `json:"id"`
	VmID      pgtype.UUID        `json:"vm_id"`
	Message   string             `json:"message"`
	Level     string             `json:"level"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type WorkerAgent struct {
	ID                     pgtype.UUID        `json:"id"`
	OrganizationID         pgtype.UUID        `json:"organization_id"`
	EnrollmentTokenID      pgtype.UUID        `json:"enrollment_token_id"`
	WorkerPublicKey        string             `json:"worker_public_key"`
	ApiTokenHash           []byte             `json:"api_token_hash"`
	Hostname               string             `json:"hostname"`
	LastSeenAt             pgtype.Timestamptz `json:"last_seen_at"`
	DesiredVersion         int32              `json:"desired_version"`
	DesiredStatePayload    []byte             `json:"desired_state_payload"`
	ReportedVersionApplied int32              `json:"reported_version_applied"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

type WorkerEnrollmentToken struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	TokenHash      []byte             `json:"token_hash"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	UsedAt         pgtype.Timestamptz `json:"used_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}
