// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type Build struct {
	ID           pgtype.UUID        `json:"id"`
	ProjectID    pgtype.UUID        `json:"project_id"`
	Status       string             `json:"status"`
	GithubCommit string             `json:"github_commit"`
	GithubBranch string             `json:"github_branch"`
	ImageID      pgtype.UUID        `json:"image_id"`
	VmID         pgtype.UUID        `json:"vm_id"`
	ProcessingBy pgtype.UUID        `json:"processing_by"`
	BuildingAt   pgtype.Timestamptz `json:"building_at"`
	FailedAt     pgtype.Timestamptz `json:"failed_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type BuildLog struct {
	ID        pgtype.UUID        `json:"id"`
	BuildID   pgtype.UUID        `json:"build_id"`
	Message   string             `json:"message"`
	Level     string             `json:"level"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type CertmagicDatum struct {
	Key      string             `json:"key"`
	Value    []byte             `json:"value"`
	Modified pgtype.Timestamptz `json:"modified"`
}

type ClusterSetting struct {
	Key       string             `json:"key"`
	Value     string             `json:"value"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Deployment struct {
	ID           pgtype.UUID        `json:"id"`
	ProjectID    pgtype.UUID        `json:"project_id"`
	BuildID      pgtype.UUID        `json:"build_id"`
	ImageID      pgtype.UUID        `json:"image_id"`
	VmID         pgtype.UUID        `json:"vm_id"`
	GithubCommit string             `json:"github_commit"`
	RunningAt    pgtype.Timestamptz `json:"running_at"`
	StoppedAt    pgtype.Timestamptz `json:"stopped_at"`
	FailedAt     pgtype.Timestamptz `json:"failed_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Domain struct {
	ID                 pgtype.UUID        `json:"id"`
	ProjectID          pgtype.UUID        `json:"project_id"`
	DeploymentID       pgtype.UUID        `json:"deployment_id"`
	DomainName         string             `json:"domain_name"`
	VerifiedAt         pgtype.Timestamptz `json:"verified_at"`
	RedirectTo         pgtype.Text        `json:"redirect_to"`
	RedirectStatusCode pgtype.Int4        `json:"redirect_status_code"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type EnvironmentVariable struct {
	ID        pgtype.UUID        `json:"id"`
	ProjectID pgtype.UUID        `json:"project_id"`
	Name      string             `json:"name"`
	Value     string             `json:"value"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Image struct {
	ID         pgtype.UUID        `json:"id"`
	Registry   string             `json:"registry"`
	Repository string             `json:"repository"`
	Tag        string             `json:"tag"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Project struct {
	ID                   pgtype.UUID        `json:"id"`
	Name                 string             `json:"name"`
	GithubRepository     string             `json:"github_repository"`
	GithubInstallationID int64              `json:"github_installation_id"`
	GithubWebhookSecret  string             `json:"github_webhook_secret"`
	RootDirectory        string             `json:"root_directory"`
	DockerfilePath       string             `json:"dockerfile_path"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type Server struct {
	ID              pgtype.UUID        `json:"id"`
	Hostname        string             `json:"hostname"`
	InternalIp      string             `json:"internal_ip"`
	IpRange         netip.Prefix       `json:"ip_range"`
	Status          string             `json:"status"`
	LastHeartbeatAt pgtype.Timestamptz `json:"last_heartbeat_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Vm struct {
	ID           pgtype.UUID        `json:"id"`
	ServerID     pgtype.UUID        `json:"server_id"`
	ImageID      pgtype.UUID        `json:"image_id"`
	Status       string             `json:"status"`
	Vcpus        int32              `json:"vcpus"`
	Memory       int32              `json:"memory"`
	IpAddress    netip.Addr         `json:"ip_address"`
	Port         pgtype.Int4        `json:"port"`
	EnvVariables pgtype.Text        `json:"env_variables"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type VmLog struct {
	ID        pgtype.UUID        `json:"id"`
	VmID      pgtype.UUID        `json:"vm_id"`
	Message   string             `json:"message"`
	Level     string             `json:"level"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
