// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package queries

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const advisoryLock = `-- name: AdvisoryLock :exec
SELECT pg_advisory_xact_lock(hashtext($1))
`

func (q *Queries) AdvisoryLock(ctx context.Context, hashtext string) error {
	_, err := q.db.Exec(ctx, advisoryLock, hashtext)
	return err
}

const buildClaimLease = `-- name: BuildClaimLease :one
UPDATE builds SET processing_by = $2, updated_at = NOW()
WHERE id = $1 AND (processing_by IS NULL OR processing_by = $2)
RETURNING id, project_id, status, github_commit, github_branch, image_id, vm_id, processing_by, building_at, failed_at, created_at, updated_at
`

type BuildClaimLeaseParams struct {
	ID           pgtype.UUID `json:"id"`
	ProcessingBy pgtype.UUID `json:"processing_by"`
}

func (q *Queries) BuildClaimLease(ctx context.Context, arg BuildClaimLeaseParams) (Build, error) {
	row := q.db.QueryRow(ctx, buildClaimLease, arg.ID, arg.ProcessingBy)
	var i Build
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Status,
		&i.GithubCommit,
		&i.GithubBranch,
		&i.ImageID,
		&i.VmID,
		&i.ProcessingBy,
		&i.BuildingAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const buildCreate = `-- name: BuildCreate :one

INSERT INTO builds (id, project_id, status, github_commit, github_branch)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, project_id, status, github_commit, github_branch, image_id, vm_id, processing_by, building_at, failed_at, created_at, updated_at
`

type BuildCreateParams struct {
	ID           pgtype.UUID `json:"id"`
	ProjectID    pgtype.UUID `json:"project_id"`
	Status       string      `json:"status"`
	GithubCommit string      `json:"github_commit"`
	GithubBranch string      `json:"github_branch"`
}

// Builds --
func (q *Queries) BuildCreate(ctx context.Context, arg BuildCreateParams) (Build, error) {
	row := q.db.QueryRow(ctx, buildCreate,
		arg.ID,
		arg.ProjectID,
		arg.Status,
		arg.GithubCommit,
		arg.GithubBranch,
	)
	var i Build
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Status,
		&i.GithubCommit,
		&i.GithubBranch,
		&i.ImageID,
		&i.VmID,
		&i.ProcessingBy,
		&i.BuildingAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const buildFirstByID = `-- name: BuildFirstByID :one
SELECT id, project_id, status, github_commit, github_branch, image_id, vm_id, processing_by, building_at, failed_at, created_at, updated_at FROM builds WHERE id = $1
`

func (q *Queries) BuildFirstByID(ctx context.Context, id pgtype.UUID) (Build, error) {
	row := q.db.QueryRow(ctx, buildFirstByID, id)
	var i Build
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Status,
		&i.GithubCommit,
		&i.GithubBranch,
		&i.ImageID,
		&i.VmID,
		&i.ProcessingBy,
		&i.BuildingAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const buildLogCreate = `-- name: BuildLogCreate :exec
INSERT INTO build_logs (id, build_id, message, level)
VALUES ($1, $2, $3, $4)
`

type BuildLogCreateParams struct {
	ID      pgtype.UUID `json:"id"`
	BuildID pgtype.UUID `json:"build_id"`
	Message string      `json:"message"`
	Level   string      `json:"level"`
}

func (q *Queries) BuildLogCreate(ctx context.Context, arg BuildLogCreateParams) error {
	_, err := q.db.Exec(ctx, buildLogCreate,
		arg.ID,
		arg.BuildID,
		arg.Message,
		arg.Level,
	)
	return err
}

const buildLogsAfterCreatedAt = `-- name: BuildLogsAfterCreatedAt :many
SELECT id, build_id, message, level, created_at FROM build_logs
WHERE build_id = $1 AND created_at > $2
ORDER BY created_at
`

type BuildLogsAfterCreatedAtParams struct {
	BuildID   pgtype.UUID        `json:"build_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) BuildLogsAfterCreatedAt(ctx context.Context, arg BuildLogsAfterCreatedAtParams) ([]BuildLog, error) {
	rows, err := q.db.Query(ctx, buildLogsAfterCreatedAt, arg.BuildID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BuildLog{}
	for rows.Next() {
		var i BuildLog
		if err := rows.Scan(
			&i.ID,
			&i.BuildID,
			&i.Message,
			&i.Level,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const buildLogsByBuildID = `-- name: BuildLogsByBuildID :many
SELECT id, build_id, message, level, created_at FROM build_logs WHERE build_id = $1 ORDER BY created_at
`

func (q *Queries) BuildLogsByBuildID(ctx context.Context, buildID pgtype.UUID) ([]BuildLog, error) {
	rows, err := q.db.Query(ctx, buildLogsByBuildID, buildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BuildLog{}
	for rows.Next() {
		var i BuildLog
		if err := rows.Scan(
			&i.ID,
			&i.BuildID,
			&i.Message,
			&i.Level,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const buildMarkBuilding = `-- name: BuildMarkBuilding :exec
UPDATE builds SET status = 'building', vm_id = $2, building_at = NOW(), updated_at = NOW()
WHERE id = $1
`

type BuildMarkBuildingParams struct {
	ID   pgtype.UUID `json:"id"`
	VmID pgtype.UUID `json:"vm_id"`
}

func (q *Queries) BuildMarkBuilding(ctx context.Context, arg BuildMarkBuildingParams) error {
	_, err := q.db.Exec(ctx, buildMarkBuilding, arg.ID, arg.VmID)
	return err
}

const buildMarkFailed = `-- name: BuildMarkFailed :exec
UPDATE builds SET status = 'failed', failed_at = NOW(), updated_at = NOW()
WHERE id = $1
`

func (q *Queries) BuildMarkFailed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, buildMarkFailed, id)
	return err
}

const buildMarkSuccessful = `-- name: BuildMarkSuccessful :exec
UPDATE builds SET status = 'successful', image_id = $2, updated_at = NOW()
WHERE id = $1
`

type BuildMarkSuccessfulParams struct {
	ID      pgtype.UUID `json:"id"`
	ImageID pgtype.UUID `json:"image_id"`
}

func (q *Queries) BuildMarkSuccessful(ctx context.Context, arg BuildMarkSuccessfulParams) error {
	_, err := q.db.Exec(ctx, buildMarkSuccessful, arg.ID, arg.ImageID)
	return err
}

const buildReleaseLease = `-- name: BuildReleaseLease :exec
UPDATE builds SET processing_by = NULL, updated_at = NOW()
WHERE id = $1 AND processing_by = $2
`

type BuildReleaseLeaseParams struct {
	ID           pgtype.UUID `json:"id"`
	ProcessingBy pgtype.UUID `json:"processing_by"`
}

func (q *Queries) BuildReleaseLease(ctx context.Context, arg BuildReleaseLeaseParams) error {
	_, err := q.db.Exec(ctx, buildReleaseLease, arg.ID, arg.ProcessingBy)
	return err
}

const certMagicDelete = `-- name: CertMagicDelete :exec
DELETE FROM certmagic_data WHERE key = $1
`

func (q *Queries) CertMagicDelete(ctx context.Context, key string) error {
	_, err := q.db.Exec(ctx, certMagicDelete, key)
	return err
}

const certMagicExists = `-- name: CertMagicExists :one
SELECT EXISTS(SELECT 1 FROM certmagic_data WHERE key = $1)
`

func (q *Queries) CertMagicExists(ctx context.Context, key string) (bool, error) {
	row := q.db.QueryRow(ctx, certMagicExists, key)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const certMagicList = `-- name: CertMagicList :many
SELECT key FROM certmagic_data WHERE key LIKE $1 ORDER BY key
`

func (q *Queries) CertMagicList(ctx context.Context, key string) ([]string, error) {
	rows, err := q.db.Query(ctx, certMagicList, key)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var key string
		if err := rows.Scan(&key); err != nil {
			return nil, err
		}
		items = append(items, key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const certMagicLoad = `-- name: CertMagicLoad :one
SELECT value, modified FROM certmagic_data WHERE key = $1
`

type CertMagicLoadRow struct {
	Value    []byte             `json:"value"`
	Modified pgtype.Timestamptz `json:"modified"`
}

func (q *Queries) CertMagicLoad(ctx context.Context, key string) (CertMagicLoadRow, error) {
	row := q.db.QueryRow(ctx, certMagicLoad, key)
	var i CertMagicLoadRow
	err := row.Scan(&i.Value, &i.Modified)
	return i, err
}

const certMagicStore = `-- name: CertMagicStore :exec

INSERT INTO certmagic_data (key, value, modified)
VALUES ($1, $2, NOW())
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, modified = NOW()
`

type CertMagicStoreParams struct {
	Key   string `json:"key"`
	Value []byte `json:"value"`
}

// CertMagic Storage --
func (q *Queries) CertMagicStore(ctx context.Context, arg CertMagicStoreParams) error {
	_, err := q.db.Exec(ctx, certMagicStore, arg.Key, arg.Value)
	return err
}

const clusterSecretDelete = `-- name: ClusterSecretDelete :exec
DELETE FROM cluster_secrets WHERE key = $1
`

func (q *Queries) ClusterSecretDelete(ctx context.Context, key string) error {
	_, err := q.db.Exec(ctx, clusterSecretDelete, key)
	return err
}

const clusterSecretGet = `-- name: ClusterSecretGet :one
SELECT ciphertext FROM cluster_secrets WHERE key = $1
`

func (q *Queries) ClusterSecretGet(ctx context.Context, key string) ([]byte, error) {
	row := q.db.QueryRow(ctx, clusterSecretGet, key)
	var ciphertext []byte
	err := row.Scan(&ciphertext)
	return ciphertext, err
}

const clusterSecretUpsert = `-- name: ClusterSecretUpsert :exec
INSERT INTO cluster_secrets (key, ciphertext, updated_at)
VALUES ($1, $2, NOW())
ON CONFLICT (key) DO UPDATE SET
    ciphertext = EXCLUDED.ciphertext,
    updated_at = NOW()
`

type ClusterSecretUpsertParams struct {
	Key        string `json:"key"`
	Ciphertext []byte `json:"ciphertext"`
}

func (q *Queries) ClusterSecretUpsert(ctx context.Context, arg ClusterSecretUpsertParams) error {
	_, err := q.db.Exec(ctx, clusterSecretUpsert, arg.Key, arg.Ciphertext)
	return err
}

const clusterSettingGet = `-- name: ClusterSettingGet :one

SELECT value FROM cluster_settings WHERE key = $1
`

// Cluster settings --
func (q *Queries) ClusterSettingGet(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRow(ctx, clusterSettingGet, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const clusterSettingUpsert = `-- name: ClusterSettingUpsert :exec
INSERT INTO cluster_settings (key, value, updated_at)
VALUES ($1, $2, NOW())
ON CONFLICT (key) DO UPDATE SET
    value = EXCLUDED.value,
    updated_at = NOW()
`

type ClusterSettingUpsertParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) ClusterSettingUpsert(ctx context.Context, arg ClusterSettingUpsertParams) error {
	_, err := q.db.Exec(ctx, clusterSettingUpsert, arg.Key, arg.Value)
	return err
}

const clusterSettingsAll = `-- name: ClusterSettingsAll :many
SELECT key, value FROM cluster_settings ORDER BY key
`

type ClusterSettingsAllRow struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) ClusterSettingsAll(ctx context.Context) ([]ClusterSettingsAllRow, error) {
	rows, err := q.db.Query(ctx, clusterSettingsAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClusterSettingsAllRow{}
	for rows.Next() {
		var i ClusterSettingsAllRow
		if err := rows.Scan(&i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deploymentClearWakeRequested = `-- name: DeploymentClearWakeRequested :exec
UPDATE deployments SET wake_requested_at = NULL, updated_at = NOW() WHERE id = $1
`

func (q *Queries) DeploymentClearWakeRequested(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deploymentClearWakeRequested, id)
	return err
}

const deploymentCreate = `-- name: DeploymentCreate :one

INSERT INTO deployments (id, project_id, github_commit)
VALUES ($1, $2, $3)
RETURNING id, project_id, build_id, image_id, vm_id, github_commit, running_at, stopped_at, failed_at, deleted_at, wake_requested_at, created_at, updated_at
`

type DeploymentCreateParams struct {
	ID           pgtype.UUID `json:"id"`
	ProjectID    pgtype.UUID `json:"project_id"`
	GithubCommit string      `json:"github_commit"`
}

// Deployments --
func (q *Queries) DeploymentCreate(ctx context.Context, arg DeploymentCreateParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, deploymentCreate, arg.ID, arg.ProjectID, arg.GithubCommit)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.BuildID,
		&i.ImageID,
		&i.VmID,
		&i.GithubCommit,
		&i.RunningAt,
		&i.StoppedAt,
		&i.FailedAt,
		&i.DeletedAt,
		&i.WakeRequestedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deploymentFindByProjectID = `-- name: DeploymentFindByProjectID :many
SELECT id, project_id, build_id, image_id, vm_id, github_commit, running_at, stopped_at, failed_at, deleted_at, wake_requested_at, created_at, updated_at FROM deployments WHERE project_id = $1 ORDER BY created_at DESC
`

func (q *Queries) DeploymentFindByProjectID(ctx context.Context, projectID pgtype.UUID) ([]Deployment, error) {
	rows, err := q.db.Query(ctx, deploymentFindByProjectID, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deployment{}
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.BuildID,
			&i.ImageID,
			&i.VmID,
			&i.GithubCommit,
			&i.RunningAt,
			&i.StoppedAt,
			&i.FailedAt,
			&i.DeletedAt,
			&i.WakeRequestedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deploymentFindByVMID = `-- name: DeploymentFindByVMID :one
SELECT d.id, d.project_id, d.build_id, d.image_id, d.vm_id, d.github_commit, d.running_at, d.stopped_at, d.failed_at, d.deleted_at, d.wake_requested_at, d.created_at, d.updated_at FROM deployments d
JOIN deployment_instances di ON di.deployment_id = d.id AND di.deleted_at IS NULL
WHERE di.vm_id = $1 AND d.deleted_at IS NULL
`

func (q *Queries) DeploymentFindByVMID(ctx context.Context, vmID pgtype.UUID) (Deployment, error) {
	row := q.db.QueryRow(ctx, deploymentFindByVMID, vmID)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.BuildID,
		&i.ImageID,
		&i.VmID,
		&i.GithubCommit,
		&i.RunningAt,
		&i.StoppedAt,
		&i.FailedAt,
		&i.DeletedAt,
		&i.WakeRequestedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deploymentFindRecentWithProject = `-- name: DeploymentFindRecentWithProject :many
SELECT
    d.id,
    d.project_id,
    d.build_id,
    d.image_id,
    d.vm_id,
    d.github_commit,
    d.running_at,
    d.stopped_at,
    d.failed_at,
    d.deleted_at,
    d.wake_requested_at,
    d.created_at,
    d.updated_at,
    p.name AS project_name,
    b.status AS build_status
FROM deployments d
JOIN projects p ON p.id = d.project_id
LEFT JOIN builds b ON d.build_id = b.id
WHERE d.deleted_at IS NULL
ORDER BY d.created_at DESC
LIMIT $1
`

type DeploymentFindRecentWithProjectRow struct {
	ID              pgtype.UUID        `json:"id"`
	ProjectID       pgtype.UUID        `json:"project_id"`
	BuildID         pgtype.UUID        `json:"build_id"`
	ImageID         pgtype.UUID        `json:"image_id"`
	VmID            pgtype.UUID        `json:"vm_id"`
	GithubCommit    string             `json:"github_commit"`
	RunningAt       pgtype.Timestamptz `json:"running_at"`
	StoppedAt       pgtype.Timestamptz `json:"stopped_at"`
	FailedAt        pgtype.Timestamptz `json:"failed_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	WakeRequestedAt pgtype.Timestamptz `json:"wake_requested_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	ProjectName     string             `json:"project_name"`
	BuildStatus     pgtype.Text        `json:"build_status"`
}

func (q *Queries) DeploymentFindRecentWithProject(ctx context.Context, limit int32) ([]DeploymentFindRecentWithProjectRow, error) {
	rows, err := q.db.Query(ctx, deploymentFindRecentWithProject, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeploymentFindRecentWithProjectRow{}
	for rows.Next() {
		var i DeploymentFindRecentWithProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.BuildID,
			&i.ImageID,
			&i.VmID,
			&i.GithubCommit,
			&i.RunningAt,
			&i.StoppedAt,
			&i.FailedAt,
			&i.DeletedAt,
			&i.WakeRequestedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProjectName,
			&i.BuildStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deploymentFindRecentWithProjectForOrg = `-- name: DeploymentFindRecentWithProjectForOrg :many
SELECT
    d.id,
    d.project_id,
    d.build_id,
    d.image_id,
    d.vm_id,
    d.github_commit,
    d.running_at,
    d.stopped_at,
    d.failed_at,
    d.deleted_at,
    d.wake_requested_at,
    d.created_at,
    d.updated_at,
    p.name AS project_name,
    b.status AS build_status
FROM deployments d
JOIN projects p ON p.id = d.project_id
LEFT JOIN builds b ON d.build_id = b.id
WHERE d.deleted_at IS NULL
  AND p.org_id = $2
ORDER BY d.created_at DESC
LIMIT $1
`

type DeploymentFindRecentWithProjectForOrgParams struct {
	Limit int32       `json:"limit"`
	OrgID pgtype.UUID `json:"org_id"`
}

type DeploymentFindRecentWithProjectForOrgRow struct {
	ID              pgtype.UUID        `json:"id"`
	ProjectID       pgtype.UUID        `json:"project_id"`
	BuildID         pgtype.UUID        `json:"build_id"`
	ImageID         pgtype.UUID        `json:"image_id"`
	VmID            pgtype.UUID        `json:"vm_id"`
	GithubCommit    string             `json:"github_commit"`
	RunningAt       pgtype.Timestamptz `json:"running_at"`
	StoppedAt       pgtype.Timestamptz `json:"stopped_at"`
	FailedAt        pgtype.Timestamptz `json:"failed_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	WakeRequestedAt pgtype.Timestamptz `json:"wake_requested_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	ProjectName     string             `json:"project_name"`
	BuildStatus     pgtype.Text        `json:"build_status"`
}

func (q *Queries) DeploymentFindRecentWithProjectForOrg(ctx context.Context, arg DeploymentFindRecentWithProjectForOrgParams) ([]DeploymentFindRecentWithProjectForOrgRow, error) {
	rows, err := q.db.Query(ctx, deploymentFindRecentWithProjectForOrg, arg.Limit, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeploymentFindRecentWithProjectForOrgRow{}
	for rows.Next() {
		var i DeploymentFindRecentWithProjectForOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.BuildID,
			&i.ImageID,
			&i.VmID,
			&i.GithubCommit,
			&i.RunningAt,
			&i.StoppedAt,
			&i.FailedAt,
			&i.DeletedAt,
			&i.WakeRequestedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProjectName,
			&i.BuildStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deploymentFindRunningAndOlder = `-- name: DeploymentFindRunningAndOlder :many
SELECT id, project_id, build_id, image_id, vm_id, github_commit, running_at, stopped_at, failed_at, deleted_at, wake_requested_at, created_at, updated_at FROM deployments
WHERE project_id = $1
  AND running_at IS NOT NULL
  AND stopped_at IS NULL
  AND failed_at IS NULL
  AND deleted_at IS NULL
  AND id != $2
ORDER BY created_at
`

type DeploymentFindRunningAndOlderParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	ID        pgtype.UUID `json:"id"`
}

func (q *Queries) DeploymentFindRunningAndOlder(ctx context.Context, arg DeploymentFindRunningAndOlderParams) ([]Deployment, error) {
	rows, err := q.db.Query(ctx, deploymentFindRunningAndOlder, arg.ProjectID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deployment{}
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.BuildID,
			&i.ImageID,
			&i.VmID,
			&i.GithubCommit,
			&i.RunningAt,
			&i.StoppedAt,
			&i.FailedAt,
			&i.DeletedAt,
			&i.WakeRequestedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deploymentFindRunningByServerID = `-- name: DeploymentFindRunningByServerID :many
SELECT DISTINCT d.id, d.project_id, d.build_id, d.image_id, d.vm_id, d.github_commit, d.running_at, d.stopped_at, d.failed_at, d.deleted_at, d.wake_requested_at, d.created_at, d.updated_at FROM deployments d
JOIN deployment_instances di ON di.deployment_id = d.id AND di.deleted_at IS NULL
JOIN vms v ON di.vm_id = v.id AND v.deleted_at IS NULL
WHERE v.server_id = $1
  AND d.running_at IS NOT NULL
  AND d.stopped_at IS NULL
  AND d.failed_at IS NULL
  AND d.deleted_at IS NULL
`

func (q *Queries) DeploymentFindRunningByServerID(ctx context.Context, serverID pgtype.UUID) ([]Deployment, error) {
	rows, err := q.db.Query(ctx, deploymentFindRunningByServerID, serverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deployment{}
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.BuildID,
			&i.ImageID,
			&i.VmID,
			&i.GithubCommit,
			&i.RunningAt,
			&i.StoppedAt,
			&i.FailedAt,
			&i.DeletedAt,
			&i.WakeRequestedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deploymentFirstByID = `-- name: DeploymentFirstByID :one
SELECT id, project_id, build_id, image_id, vm_id, github_commit, running_at, stopped_at, failed_at, deleted_at, wake_requested_at, created_at, updated_at FROM deployments WHERE id = $1
`

func (q *Queries) DeploymentFirstByID(ctx context.Context, id pgtype.UUID) (Deployment, error) {
	row := q.db.QueryRow(ctx, deploymentFirstByID, id)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.BuildID,
		&i.ImageID,
		&i.VmID,
		&i.GithubCommit,
		&i.RunningAt,
		&i.StoppedAt,
		&i.FailedAt,
		&i.DeletedAt,
		&i.WakeRequestedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deploymentInstanceAttachVM = `-- name: DeploymentInstanceAttachVM :one
UPDATE deployment_instances SET vm_id = $2, status = $3, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, deployment_id, server_id, vm_id, status, deleted_at, created_at, updated_at
`

type DeploymentInstanceAttachVMParams struct {
	ID     pgtype.UUID `json:"id"`
	VmID   pgtype.UUID `json:"vm_id"`
	Status string      `json:"status"`
}

func (q *Queries) DeploymentInstanceAttachVM(ctx context.Context, arg DeploymentInstanceAttachVMParams) (DeploymentInstance, error) {
	row := q.db.QueryRow(ctx, deploymentInstanceAttachVM, arg.ID, arg.VmID, arg.Status)
	var i DeploymentInstance
	err := row.Scan(
		&i.ID,
		&i.DeploymentID,
		&i.ServerID,
		&i.VmID,
		&i.Status,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deploymentInstanceCreate = `-- name: DeploymentInstanceCreate :one

INSERT INTO deployment_instances (id, deployment_id, status)
VALUES ($1, $2, 'pending')
RETURNING id, deployment_id, server_id, vm_id, status, deleted_at, created_at, updated_at
`

type DeploymentInstanceCreateParams struct {
	ID           pgtype.UUID `json:"id"`
	DeploymentID pgtype.UUID `json:"deployment_id"`
}

// Deployment instances (horizontal scaling) --
func (q *Queries) DeploymentInstanceCreate(ctx context.Context, arg DeploymentInstanceCreateParams) (DeploymentInstance, error) {
	row := q.db.QueryRow(ctx, deploymentInstanceCreate, arg.ID, arg.DeploymentID)
	var i DeploymentInstance
	err := row.Scan(
		&i.ID,
		&i.DeploymentID,
		&i.ServerID,
		&i.VmID,
		&i.Status,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deploymentInstanceFindByDeploymentID = `-- name: DeploymentInstanceFindByDeploymentID :many
SELECT id, deployment_id, server_id, vm_id, status, deleted_at, created_at, updated_at FROM deployment_instances
WHERE deployment_id = $1 AND deleted_at IS NULL
ORDER BY created_at ASC
`

func (q *Queries) DeploymentInstanceFindByDeploymentID(ctx context.Context, deploymentID pgtype.UUID) ([]DeploymentInstance, error) {
	rows, err := q.db.Query(ctx, deploymentInstanceFindByDeploymentID, deploymentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeploymentInstance{}
	for rows.Next() {
		var i DeploymentInstance
		if err := rows.Scan(
			&i.ID,
			&i.DeploymentID,
			&i.ServerID,
			&i.VmID,
			&i.Status,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deploymentInstanceFirstByID = `-- name: DeploymentInstanceFirstByID :one
SELECT id, deployment_id, server_id, vm_id, status, deleted_at, created_at, updated_at FROM deployment_instances WHERE id = $1
`

func (q *Queries) DeploymentInstanceFirstByID(ctx context.Context, id pgtype.UUID) (DeploymentInstance, error) {
	row := q.db.QueryRow(ctx, deploymentInstanceFirstByID, id)
	var i DeploymentInstance
	err := row.Scan(
		&i.ID,
		&i.DeploymentID,
		&i.ServerID,
		&i.VmID,
		&i.Status,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deploymentInstancePrepareRetry = `-- name: DeploymentInstancePrepareRetry :one
UPDATE deployment_instances
SET server_id = NULL, vm_id = NULL, status = 'pending', updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, deployment_id, server_id, vm_id, status, deleted_at, created_at, updated_at
`

func (q *Queries) DeploymentInstancePrepareRetry(ctx context.Context, id pgtype.UUID) (DeploymentInstance, error) {
	row := q.db.QueryRow(ctx, deploymentInstancePrepareRetry, id)
	var i DeploymentInstance
	err := row.Scan(
		&i.ID,
		&i.DeploymentID,
		&i.ServerID,
		&i.VmID,
		&i.Status,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deploymentInstanceResetForDeadServer = `-- name: DeploymentInstanceResetForDeadServer :exec
UPDATE deployment_instances
SET server_id = NULL, vm_id = NULL, status = 'pending', updated_at = NOW()
WHERE server_id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeploymentInstanceResetForDeadServer(ctx context.Context, serverID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deploymentInstanceResetForDeadServer, serverID)
	return err
}

const deploymentInstanceSoftDelete = `-- name: DeploymentInstanceSoftDelete :exec
UPDATE deployment_instances SET deleted_at = NOW(), updated_at = NOW() WHERE id = $1
`

func (q *Queries) DeploymentInstanceSoftDelete(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deploymentInstanceSoftDelete, id)
	return err
}

const deploymentInstanceSoftDeleteByDeploymentID = `-- name: DeploymentInstanceSoftDeleteByDeploymentID :exec
UPDATE deployment_instances SET deleted_at = NOW(), updated_at = NOW()
WHERE deployment_id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeploymentInstanceSoftDeleteByDeploymentID(ctx context.Context, deploymentID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deploymentInstanceSoftDeleteByDeploymentID, deploymentID)
	return err
}

const deploymentInstanceUpdateServer = `-- name: DeploymentInstanceUpdateServer :one
UPDATE deployment_instances SET server_id = $2, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, deployment_id, server_id, vm_id, status, deleted_at, created_at, updated_at
`

type DeploymentInstanceUpdateServerParams struct {
	ID       pgtype.UUID `json:"id"`
	ServerID pgtype.UUID `json:"server_id"`
}

func (q *Queries) DeploymentInstanceUpdateServer(ctx context.Context, arg DeploymentInstanceUpdateServerParams) (DeploymentInstance, error) {
	row := q.db.QueryRow(ctx, deploymentInstanceUpdateServer, arg.ID, arg.ServerID)
	var i DeploymentInstance
	err := row.Scan(
		&i.ID,
		&i.DeploymentID,
		&i.ServerID,
		&i.VmID,
		&i.Status,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deploymentInstanceUpdateStatus = `-- name: DeploymentInstanceUpdateStatus :one
UPDATE deployment_instances SET status = $2, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, deployment_id, server_id, vm_id, status, deleted_at, created_at, updated_at
`

type DeploymentInstanceUpdateStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) DeploymentInstanceUpdateStatus(ctx context.Context, arg DeploymentInstanceUpdateStatusParams) (DeploymentInstance, error) {
	row := q.db.QueryRow(ctx, deploymentInstanceUpdateStatus, arg.ID, arg.Status)
	var i DeploymentInstance
	err := row.Scan(
		&i.ID,
		&i.DeploymentID,
		&i.ServerID,
		&i.VmID,
		&i.Status,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deploymentInstanceVMIDsByServerID = `-- name: DeploymentInstanceVMIDsByServerID :many
SELECT vm_id FROM deployment_instances
WHERE server_id = $1 AND deleted_at IS NULL AND vm_id IS NOT NULL
`

func (q *Queries) DeploymentInstanceVMIDsByServerID(ctx context.Context, serverID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, deploymentInstanceVMIDsByServerID, serverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var vm_id pgtype.UUID
		if err := rows.Scan(&vm_id); err != nil {
			return nil, err
		}
		items = append(items, vm_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deploymentInstancesRunningForUsageOnServer = `-- name: DeploymentInstancesRunningForUsageOnServer :many
SELECT
    di.id,
    di.deployment_id,
    d.project_id
FROM deployment_instances di
INNER JOIN deployments d ON d.id = di.deployment_id AND d.deleted_at IS NULL
WHERE di.server_id = $1
  AND di.deleted_at IS NULL
  AND di.status = 'running'
  AND di.vm_id IS NOT NULL
`

type DeploymentInstancesRunningForUsageOnServerRow struct {
	ID           pgtype.UUID `json:"id"`
	DeploymentID pgtype.UUID `json:"deployment_id"`
	ProjectID    pgtype.UUID `json:"project_id"`
}

func (q *Queries) DeploymentInstancesRunningForUsageOnServer(ctx context.Context, serverID pgtype.UUID) ([]DeploymentInstancesRunningForUsageOnServerRow, error) {
	rows, err := q.db.Query(ctx, deploymentInstancesRunningForUsageOnServer, serverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeploymentInstancesRunningForUsageOnServerRow{}
	for rows.Next() {
		var i DeploymentInstancesRunningForUsageOnServerRow
		if err := rows.Scan(&i.ID, &i.DeploymentID, &i.ProjectID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deploymentLatestRunningByProjectID = `-- name: DeploymentLatestRunningByProjectID :one
SELECT id, project_id, build_id, image_id, vm_id, github_commit, running_at, stopped_at, failed_at, deleted_at, wake_requested_at, created_at, updated_at FROM deployments
WHERE project_id = $1
  AND running_at IS NOT NULL
  AND stopped_at IS NULL
  AND failed_at IS NULL
  AND deleted_at IS NULL
ORDER BY running_at DESC
LIMIT 1
`

func (q *Queries) DeploymentLatestRunningByProjectID(ctx context.Context, projectID pgtype.UUID) (Deployment, error) {
	row := q.db.QueryRow(ctx, deploymentLatestRunningByProjectID, projectID)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.BuildID,
		&i.ImageID,
		&i.VmID,
		&i.GithubCommit,
		&i.RunningAt,
		&i.StoppedAt,
		&i.FailedAt,
		&i.DeletedAt,
		&i.WakeRequestedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deploymentMarkRunning = `-- name: DeploymentMarkRunning :exec
UPDATE deployments SET running_at = NOW(), updated_at = NOW() WHERE id = $1
`

func (q *Queries) DeploymentMarkRunning(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deploymentMarkRunning, id)
	return err
}

const deploymentMarkStopped = `-- name: DeploymentMarkStopped :exec
UPDATE deployments SET stopped_at = NOW(), updated_at = NOW() WHERE id = $1
`

func (q *Queries) DeploymentMarkStopped(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deploymentMarkStopped, id)
	return err
}

const deploymentRequestWake = `-- name: DeploymentRequestWake :one
UPDATE deployments
SET wake_requested_at = COALESCE(wake_requested_at, NOW()), updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL AND failed_at IS NULL AND stopped_at IS NULL
RETURNING id, project_id, build_id, image_id, vm_id, github_commit, running_at, stopped_at, failed_at, deleted_at, wake_requested_at, created_at, updated_at
`

func (q *Queries) DeploymentRequestWake(ctx context.Context, id pgtype.UUID) (Deployment, error) {
	row := q.db.QueryRow(ctx, deploymentRequestWake, id)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.BuildID,
		&i.ImageID,
		&i.VmID,
		&i.GithubCommit,
		&i.RunningAt,
		&i.StoppedAt,
		&i.FailedAt,
		&i.DeletedAt,
		&i.WakeRequestedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deploymentUpdateBuild = `-- name: DeploymentUpdateBuild :one
UPDATE deployments SET build_id = $2, updated_at = NOW() WHERE id = $1 RETURNING id, project_id, build_id, image_id, vm_id, github_commit, running_at, stopped_at, failed_at, deleted_at, wake_requested_at, created_at, updated_at
`

type DeploymentUpdateBuildParams struct {
	ID      pgtype.UUID `json:"id"`
	BuildID pgtype.UUID `json:"build_id"`
}

func (q *Queries) DeploymentUpdateBuild(ctx context.Context, arg DeploymentUpdateBuildParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, deploymentUpdateBuild, arg.ID, arg.BuildID)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.BuildID,
		&i.ImageID,
		&i.VmID,
		&i.GithubCommit,
		&i.RunningAt,
		&i.StoppedAt,
		&i.FailedAt,
		&i.DeletedAt,
		&i.WakeRequestedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deploymentUpdateFailedAt = `-- name: DeploymentUpdateFailedAt :exec
UPDATE deployments SET failed_at = NOW(), updated_at = NOW() WHERE id = $1
`

func (q *Queries) DeploymentUpdateFailedAt(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deploymentUpdateFailedAt, id)
	return err
}

const deploymentUpdateImage = `-- name: DeploymentUpdateImage :one
UPDATE deployments SET image_id = $2, updated_at = NOW() WHERE id = $1 RETURNING id, project_id, build_id, image_id, vm_id, github_commit, running_at, stopped_at, failed_at, deleted_at, wake_requested_at, created_at, updated_at
`

type DeploymentUpdateImageParams struct {
	ID      pgtype.UUID `json:"id"`
	ImageID pgtype.UUID `json:"image_id"`
}

func (q *Queries) DeploymentUpdateImage(ctx context.Context, arg DeploymentUpdateImageParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, deploymentUpdateImage, arg.ID, arg.ImageID)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.BuildID,
		&i.ImageID,
		&i.VmID,
		&i.GithubCommit,
		&i.RunningAt,
		&i.StoppedAt,
		&i.FailedAt,
		&i.DeletedAt,
		&i.WakeRequestedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deploymentUpdateVM = `-- name: DeploymentUpdateVM :one
UPDATE deployments SET vm_id = $2, updated_at = NOW() WHERE id = $1 RETURNING id, project_id, build_id, image_id, vm_id, github_commit, running_at, stopped_at, failed_at, deleted_at, wake_requested_at, created_at, updated_at
`

type DeploymentUpdateVMParams struct {
	ID   pgtype.UUID `json:"id"`
	VmID pgtype.UUID `json:"vm_id"`
}

func (q *Queries) DeploymentUpdateVM(ctx context.Context, arg DeploymentUpdateVMParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, deploymentUpdateVM, arg.ID, arg.VmID)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.BuildID,
		&i.ImageID,
		&i.VmID,
		&i.GithubCommit,
		&i.RunningAt,
		&i.StoppedAt,
		&i.FailedAt,
		&i.DeletedAt,
		&i.WakeRequestedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const domainCreate = `-- name: DomainCreate :one

INSERT INTO domains (id, project_id, domain_name, verification_token)
VALUES ($1, $2, $3, $4)
RETURNING id, project_id, deployment_id, domain_name, verification_token, verified_at, redirect_to, redirect_status_code, created_at, updated_at
`

type DomainCreateParams struct {
	ID                pgtype.UUID `json:"id"`
	ProjectID         pgtype.UUID `json:"project_id"`
	DomainName        string      `json:"domain_name"`
	VerificationToken string      `json:"verification_token"`
}

// Domains --
func (q *Queries) DomainCreate(ctx context.Context, arg DomainCreateParams) (Domain, error) {
	row := q.db.QueryRow(ctx, domainCreate,
		arg.ID,
		arg.ProjectID,
		arg.DomainName,
		arg.VerificationToken,
	)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.DeploymentID,
		&i.DomainName,
		&i.VerificationToken,
		&i.VerifiedAt,
		&i.RedirectTo,
		&i.RedirectStatusCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const domainDelete = `-- name: DomainDelete :exec
DELETE FROM domains WHERE id = $1 AND project_id = $2
`

type DomainDeleteParams struct {
	ID        pgtype.UUID `json:"id"`
	ProjectID pgtype.UUID `json:"project_id"`
}

func (q *Queries) DomainDelete(ctx context.Context, arg DomainDeleteParams) error {
	_, err := q.db.Exec(ctx, domainDelete, arg.ID, arg.ProjectID)
	return err
}

const domainEdgeLookup = `-- name: DomainEdgeLookup :one
SELECT
    d.id AS domain_id,
    d.project_id,
    d.deployment_id,
    d.redirect_to,
    d.redirect_status_code,
    dep.wake_requested_at AS deployment_wake_requested_at,
    (SELECT COUNT(*)::bigint FROM deployment_instances di
     INNER JOIN vms vm ON di.vm_id = vm.id AND vm.deleted_at IS NULL AND vm.status = 'running'
     WHERE di.deployment_id = d.deployment_id AND di.deleted_at IS NULL AND di.status = 'running') AS running_backend_count
FROM domains d
LEFT JOIN deployments dep ON d.deployment_id = dep.id AND dep.deleted_at IS NULL
WHERE d.domain_name = $1 AND d.verified_at IS NOT NULL
`

type DomainEdgeLookupRow struct {
	DomainID                  pgtype.UUID        `json:"domain_id"`
	ProjectID                 pgtype.UUID        `json:"project_id"`
	DeploymentID              pgtype.UUID        `json:"deployment_id"`
	RedirectTo                pgtype.Text        `json:"redirect_to"`
	RedirectStatusCode        pgtype.Int4        `json:"redirect_status_code"`
	DeploymentWakeRequestedAt pgtype.Timestamptz `json:"deployment_wake_requested_at"`
	RunningBackendCount       int64              `json:"running_backend_count"`
}

func (q *Queries) DomainEdgeLookup(ctx context.Context, domainName string) (DomainEdgeLookupRow, error) {
	row := q.db.QueryRow(ctx, domainEdgeLookup, domainName)
	var i DomainEdgeLookupRow
	err := row.Scan(
		&i.DomainID,
		&i.ProjectID,
		&i.DeploymentID,
		&i.RedirectTo,
		&i.RedirectStatusCode,
		&i.DeploymentWakeRequestedAt,
		&i.RunningBackendCount,
	)
	return i, err
}

const domainFindVerifiedByDeploymentID = `-- name: DomainFindVerifiedByDeploymentID :many
SELECT id, project_id, deployment_id, domain_name, verification_token, verified_at, redirect_to, redirect_status_code, created_at, updated_at
FROM domains
WHERE deployment_id = $1
  AND verified_at IS NOT NULL
ORDER BY domain_name ASC
`

func (q *Queries) DomainFindVerifiedByDeploymentID(ctx context.Context, deploymentID pgtype.UUID) ([]Domain, error) {
	rows, err := q.db.Query(ctx, domainFindVerifiedByDeploymentID, deploymentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Domain{}
	for rows.Next() {
		var i Domain
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.DeploymentID,
			&i.DomainName,
			&i.VerificationToken,
			&i.VerifiedAt,
			&i.RedirectTo,
			&i.RedirectStatusCode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const domainFirstByIDAndProject = `-- name: DomainFirstByIDAndProject :one
SELECT id, project_id, deployment_id, domain_name, verification_token, verified_at, redirect_to, redirect_status_code, created_at, updated_at FROM domains WHERE id = $1 AND project_id = $2
`

type DomainFirstByIDAndProjectParams struct {
	ID        pgtype.UUID `json:"id"`
	ProjectID pgtype.UUID `json:"project_id"`
}

func (q *Queries) DomainFirstByIDAndProject(ctx context.Context, arg DomainFirstByIDAndProjectParams) (Domain, error) {
	row := q.db.QueryRow(ctx, domainFirstByIDAndProject, arg.ID, arg.ProjectID)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.DeploymentID,
		&i.DomainName,
		&i.VerificationToken,
		&i.VerifiedAt,
		&i.RedirectTo,
		&i.RedirectStatusCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const domainListByProjectID = `-- name: DomainListByProjectID :many
SELECT id, project_id, deployment_id, domain_name, verification_token, verified_at, redirect_to, redirect_status_code, created_at, updated_at FROM domains WHERE project_id = $1 ORDER BY domain_name ASC
`

func (q *Queries) DomainListByProjectID(ctx context.Context, projectID pgtype.UUID) ([]Domain, error) {
	rows, err := q.db.Query(ctx, domainListByProjectID, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Domain{}
	for rows.Next() {
		var i Domain
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.DeploymentID,
			&i.DomainName,
			&i.VerificationToken,
			&i.VerifiedAt,
			&i.RedirectTo,
			&i.RedirectStatusCode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const domainSetVerified = `-- name: DomainSetVerified :one
UPDATE domains
SET verified_at = NOW(), verification_token = '', updated_at = NOW()
WHERE id = $1 AND project_id = $2
RETURNING id, project_id, deployment_id, domain_name, verification_token, verified_at, redirect_to, redirect_status_code, created_at, updated_at
`

type DomainSetVerifiedParams struct {
	ID        pgtype.UUID `json:"id"`
	ProjectID pgtype.UUID `json:"project_id"`
}

func (q *Queries) DomainSetVerified(ctx context.Context, arg DomainSetVerifiedParams) (Domain, error) {
	row := q.db.QueryRow(ctx, domainSetVerified, arg.ID, arg.ProjectID)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.DeploymentID,
		&i.DomainName,
		&i.VerificationToken,
		&i.VerifiedAt,
		&i.RedirectTo,
		&i.RedirectStatusCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const domainUpdateDeploymentForProject = `-- name: DomainUpdateDeploymentForProject :exec
UPDATE domains SET deployment_id = $1, updated_at = NOW() WHERE project_id = $2
`

type DomainUpdateDeploymentForProjectParams struct {
	DeploymentID pgtype.UUID `json:"deployment_id"`
	ProjectID    pgtype.UUID `json:"project_id"`
}

func (q *Queries) DomainUpdateDeploymentForProject(ctx context.Context, arg DomainUpdateDeploymentForProjectParams) error {
	_, err := q.db.Exec(ctx, domainUpdateDeploymentForProject, arg.DeploymentID, arg.ProjectID)
	return err
}

const domainVerified = `-- name: DomainVerified :one
SELECT verified_at FROM domains WHERE domain_name = $1
`

func (q *Queries) DomainVerified(ctx context.Context, domainName string) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, domainVerified, domainName)
	var verified_at pgtype.Timestamptz
	err := row.Scan(&verified_at)
	return verified_at, err
}

const environmentVariableCreate = `-- name: EnvironmentVariableCreate :one

INSERT INTO environment_variables (id, project_id, name, value)
VALUES ($1, $2, $3, $4)
ON CONFLICT (project_id, name) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW()
RETURNING id, project_id, name, value, created_at, updated_at
`

type EnvironmentVariableCreateParams struct {
	ID        pgtype.UUID `json:"id"`
	ProjectID pgtype.UUID `json:"project_id"`
	Name      string      `json:"name"`
	Value     string      `json:"value"`
}

// Environment Variables --
func (q *Queries) EnvironmentVariableCreate(ctx context.Context, arg EnvironmentVariableCreateParams) (EnvironmentVariable, error) {
	row := q.db.QueryRow(ctx, environmentVariableCreate,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.Value,
	)
	var i EnvironmentVariable
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const environmentVariableDelete = `-- name: EnvironmentVariableDelete :exec
DELETE FROM environment_variables WHERE id = $1
`

func (q *Queries) EnvironmentVariableDelete(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, environmentVariableDelete, id)
	return err
}

const environmentVariableFindByProjectID = `-- name: EnvironmentVariableFindByProjectID :many
SELECT id, project_id, name, value, created_at, updated_at FROM environment_variables WHERE project_id = $1 ORDER BY name
`

func (q *Queries) EnvironmentVariableFindByProjectID(ctx context.Context, projectID pgtype.UUID) ([]EnvironmentVariable, error) {
	rows, err := q.db.Query(ctx, environmentVariableFindByProjectID, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EnvironmentVariable{}
	for rows.Next() {
		var i EnvironmentVariable
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Value,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const imageFindByID = `-- name: ImageFindByID :one
SELECT id, registry, repository, tag, created_at FROM images WHERE id = $1
`

func (q *Queries) ImageFindByID(ctx context.Context, id pgtype.UUID) (Image, error) {
	row := q.db.QueryRow(ctx, imageFindByID, id)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.Registry,
		&i.Repository,
		&i.Tag,
		&i.CreatedAt,
	)
	return i, err
}

const imageFindOrCreate = `-- name: ImageFindOrCreate :one

INSERT INTO images (id, registry, repository, tag)
VALUES ($1, $2, $3, $4)
ON CONFLICT (registry, repository, tag) DO UPDATE SET registry = EXCLUDED.registry
RETURNING id, registry, repository, tag, created_at
`

type ImageFindOrCreateParams struct {
	ID         pgtype.UUID `json:"id"`
	Registry   string      `json:"registry"`
	Repository string      `json:"repository"`
	Tag        string      `json:"tag"`
}

// Images --
func (q *Queries) ImageFindOrCreate(ctx context.Context, arg ImageFindOrCreateParams) (Image, error) {
	row := q.db.QueryRow(ctx, imageFindOrCreate,
		arg.ID,
		arg.Registry,
		arg.Repository,
		arg.Tag,
	)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.Registry,
		&i.Repository,
		&i.Tag,
		&i.CreatedAt,
	)
	return i, err
}

const instanceUsageLastBefore = `-- name: InstanceUsageLastBefore :one
SELECT sampled_at, cpu_nanos_cumulative
FROM instance_usage_samples
WHERE deployment_instance_id = $1
  AND sampled_at < $2
ORDER BY sampled_at DESC
LIMIT 1
`

type InstanceUsageLastBeforeParams struct {
	DeploymentInstanceID pgtype.UUID        `json:"deployment_instance_id"`
	SampledAt            pgtype.Timestamptz `json:"sampled_at"`
}

type InstanceUsageLastBeforeRow struct {
	SampledAt          pgtype.Timestamptz `json:"sampled_at"`
	CpuNanosCumulative int64              `json:"cpu_nanos_cumulative"`
}

func (q *Queries) InstanceUsageLastBefore(ctx context.Context, arg InstanceUsageLastBeforeParams) (InstanceUsageLastBeforeRow, error) {
	row := q.db.QueryRow(ctx, instanceUsageLastBefore, arg.DeploymentInstanceID, arg.SampledAt)
	var i InstanceUsageLastBeforeRow
	err := row.Scan(&i.SampledAt, &i.CpuNanosCumulative)
	return i, err
}

const instanceUsageLatestPerInstance = `-- name: InstanceUsageLatestPerInstance :many
SELECT DISTINCT ON (deployment_instance_id)
    deployment_instance_id,
    sampled_at,
    cpu_nanos_cumulative,
    cpu_percent,
    memory_rss_bytes,
    disk_read_bytes,
    disk_write_bytes,
    source,
    server_id
FROM instance_usage_samples
WHERE project_id = $1
  AND sampled_at >= $2
ORDER BY deployment_instance_id, sampled_at DESC
`

type InstanceUsageLatestPerInstanceParams struct {
	ProjectID pgtype.UUID        `json:"project_id"`
	SampledAt pgtype.Timestamptz `json:"sampled_at"`
}

type InstanceUsageLatestPerInstanceRow struct {
	DeploymentInstanceID pgtype.UUID        `json:"deployment_instance_id"`
	SampledAt            pgtype.Timestamptz `json:"sampled_at"`
	CpuNanosCumulative   int64              `json:"cpu_nanos_cumulative"`
	CpuPercent           pgtype.Float8      `json:"cpu_percent"`
	MemoryRssBytes       int64              `json:"memory_rss_bytes"`
	DiskReadBytes        int64              `json:"disk_read_bytes"`
	DiskWriteBytes       int64              `json:"disk_write_bytes"`
	Source               string             `json:"source"`
	ServerID             pgtype.UUID        `json:"server_id"`
}

func (q *Queries) InstanceUsageLatestPerInstance(ctx context.Context, arg InstanceUsageLatestPerInstanceParams) ([]InstanceUsageLatestPerInstanceRow, error) {
	rows, err := q.db.Query(ctx, instanceUsageLatestPerInstance, arg.ProjectID, arg.SampledAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InstanceUsageLatestPerInstanceRow{}
	for rows.Next() {
		var i InstanceUsageLatestPerInstanceRow
		if err := rows.Scan(
			&i.DeploymentInstanceID,
			&i.SampledAt,
			&i.CpuNanosCumulative,
			&i.CpuPercent,
			&i.MemoryRssBytes,
			&i.DiskReadBytes,
			&i.DiskWriteBytes,
			&i.Source,
			&i.ServerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const instanceUsageSampleInsert = `-- name: InstanceUsageSampleInsert :exec

INSERT INTO instance_usage_samples (
    id, server_id, project_id, deployment_id, deployment_instance_id,
    sampled_at, cpu_nanos_cumulative, cpu_percent, memory_rss_bytes, disk_read_bytes, disk_write_bytes, source
) VALUES (
    $1, $2, $3, $4, $5, NOW(), $6, $7, $8, $9, $10, $11
)
`

type InstanceUsageSampleInsertParams struct {
	ID                   pgtype.UUID   `json:"id"`
	ServerID             pgtype.UUID   `json:"server_id"`
	ProjectID            pgtype.UUID   `json:"project_id"`
	DeploymentID         pgtype.UUID   `json:"deployment_id"`
	DeploymentInstanceID pgtype.UUID   `json:"deployment_instance_id"`
	CpuNanosCumulative   int64         `json:"cpu_nanos_cumulative"`
	CpuPercent           pgtype.Float8 `json:"cpu_percent"`
	MemoryRssBytes       int64         `json:"memory_rss_bytes"`
	DiskReadBytes        int64         `json:"disk_read_bytes"`
	DiskWriteBytes       int64         `json:"disk_write_bytes"`
	Source               string        `json:"source"`
}

// Usage metrics --
func (q *Queries) InstanceUsageSampleInsert(ctx context.Context, arg InstanceUsageSampleInsertParams) error {
	_, err := q.db.Exec(ctx, instanceUsageSampleInsert,
		arg.ID,
		arg.ServerID,
		arg.ProjectID,
		arg.DeploymentID,
		arg.DeploymentInstanceID,
		arg.CpuNanosCumulative,
		arg.CpuPercent,
		arg.MemoryRssBytes,
		arg.DiskReadBytes,
		arg.DiskWriteBytes,
		arg.Source,
	)
	return err
}

const instanceUsageSamplesByProjectWindow = `-- name: InstanceUsageSamplesByProjectWindow :many
SELECT
    date_trunc('minute', sampled_at)::timestamptz AS bucket_start,
    COALESCE(MAX(memory_rss_bytes), 0)::bigint AS memory_rss_bytes_max,
    COALESCE(AVG(cpu_percent), 0)::float8 AS cpu_percent_avg
FROM instance_usage_samples
WHERE project_id = $1
  AND sampled_at >= $2
  AND sampled_at <= $3
GROUP BY 1
ORDER BY 1 ASC
`

type InstanceUsageSamplesByProjectWindowParams struct {
	ProjectID   pgtype.UUID        `json:"project_id"`
	SampledAt   pgtype.Timestamptz `json:"sampled_at"`
	SampledAt_2 pgtype.Timestamptz `json:"sampled_at_2"`
}

type InstanceUsageSamplesByProjectWindowRow struct {
	BucketStart       pgtype.Timestamptz `json:"bucket_start"`
	MemoryRssBytesMax int64              `json:"memory_rss_bytes_max"`
	CpuPercentAvg     float64            `json:"cpu_percent_avg"`
}

func (q *Queries) InstanceUsageSamplesByProjectWindow(ctx context.Context, arg InstanceUsageSamplesByProjectWindowParams) ([]InstanceUsageSamplesByProjectWindowRow, error) {
	rows, err := q.db.Query(ctx, instanceUsageSamplesByProjectWindow, arg.ProjectID, arg.SampledAt, arg.SampledAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InstanceUsageSamplesByProjectWindowRow{}
	for rows.Next() {
		var i InstanceUsageSamplesByProjectWindowRow
		if err := rows.Scan(&i.BucketStart, &i.MemoryRssBytesMax, &i.CpuPercentAvg); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const orgProviderConnectionByIDAndOrg = `-- name: OrgProviderConnectionByIDAndOrg :one
SELECT id, organization_id, provider, external_slug, display_label, credentials_ciphertext, metadata, created_at, updated_at FROM org_provider_connections
WHERE id = $1 AND organization_id = $2
`

type OrgProviderConnectionByIDAndOrgParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) OrgProviderConnectionByIDAndOrg(ctx context.Context, arg OrgProviderConnectionByIDAndOrgParams) (OrgProviderConnection, error) {
	row := q.db.QueryRow(ctx, orgProviderConnectionByIDAndOrg, arg.ID, arg.OrganizationID)
	var i OrgProviderConnection
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Provider,
		&i.ExternalSlug,
		&i.DisplayLabel,
		&i.CredentialsCiphertext,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const orgProviderConnectionCreate = `-- name: OrgProviderConnectionCreate :one
INSERT INTO org_provider_connections (
    id, organization_id, provider, external_slug, display_label, credentials_ciphertext, metadata
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, organization_id, provider, external_slug, display_label, credentials_ciphertext, metadata, created_at, updated_at
`

type OrgProviderConnectionCreateParams struct {
	ID                    pgtype.UUID `json:"id"`
	OrganizationID        pgtype.UUID `json:"organization_id"`
	Provider              string      `json:"provider"`
	ExternalSlug          string      `json:"external_slug"`
	DisplayLabel          string      `json:"display_label"`
	CredentialsCiphertext []byte      `json:"credentials_ciphertext"`
	Metadata              []byte      `json:"metadata"`
}

func (q *Queries) OrgProviderConnectionCreate(ctx context.Context, arg OrgProviderConnectionCreateParams) (OrgProviderConnection, error) {
	row := q.db.QueryRow(ctx, orgProviderConnectionCreate,
		arg.ID,
		arg.OrganizationID,
		arg.Provider,
		arg.ExternalSlug,
		arg.DisplayLabel,
		arg.CredentialsCiphertext,
		arg.Metadata,
	)
	var i OrgProviderConnection
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Provider,
		&i.ExternalSlug,
		&i.DisplayLabel,
		&i.CredentialsCiphertext,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const orgProviderConnectionDeleteByIDAndOrg = `-- name: OrgProviderConnectionDeleteByIDAndOrg :exec
DELETE FROM org_provider_connections WHERE id = $1 AND organization_id = $2
`

type OrgProviderConnectionDeleteByIDAndOrgParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) OrgProviderConnectionDeleteByIDAndOrg(ctx context.Context, arg OrgProviderConnectionDeleteByIDAndOrgParams) error {
	_, err := q.db.Exec(ctx, orgProviderConnectionDeleteByIDAndOrg, arg.ID, arg.OrganizationID)
	return err
}

const orgProviderConnectionListByOrg = `-- name: OrgProviderConnectionListByOrg :many
SELECT id, organization_id, provider, external_slug, display_label, credentials_ciphertext, metadata, created_at, updated_at FROM org_provider_connections
WHERE organization_id = $1
ORDER BY provider ASC, display_label ASC
`

func (q *Queries) OrgProviderConnectionListByOrg(ctx context.Context, organizationID pgtype.UUID) ([]OrgProviderConnection, error) {
	rows, err := q.db.Query(ctx, orgProviderConnectionListByOrg, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrgProviderConnection{}
	for rows.Next() {
		var i OrgProviderConnection
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Provider,
			&i.ExternalSlug,
			&i.DisplayLabel,
			&i.CredentialsCiphertext,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const orgProviderConnectionUpdate = `-- name: OrgProviderConnectionUpdate :one
UPDATE org_provider_connections
SET display_label = $2,
    external_slug = $3,
    credentials_ciphertext = $4,
    metadata = $5,
    updated_at = NOW()
WHERE id = $1 AND organization_id = $6
RETURNING id, organization_id, provider, external_slug, display_label, credentials_ciphertext, metadata, created_at, updated_at
`

type OrgProviderConnectionUpdateParams struct {
	ID                    pgtype.UUID `json:"id"`
	DisplayLabel          string      `json:"display_label"`
	ExternalSlug          string      `json:"external_slug"`
	CredentialsCiphertext []byte      `json:"credentials_ciphertext"`
	Metadata              []byte      `json:"metadata"`
	OrganizationID        pgtype.UUID `json:"organization_id"`
}

func (q *Queries) OrgProviderConnectionUpdate(ctx context.Context, arg OrgProviderConnectionUpdateParams) (OrgProviderConnection, error) {
	row := q.db.QueryRow(ctx, orgProviderConnectionUpdate,
		arg.ID,
		arg.DisplayLabel,
		arg.ExternalSlug,
		arg.CredentialsCiphertext,
		arg.Metadata,
		arg.OrganizationID,
	)
	var i OrgProviderConnection
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Provider,
		&i.ExternalSlug,
		&i.DisplayLabel,
		&i.CredentialsCiphertext,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const organizationByID = `-- name: OrganizationByID :one
SELECT id, name, slug, created_at, updated_at FROM organizations WHERE id = $1
`

func (q *Queries) OrganizationByID(ctx context.Context, id pgtype.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, organizationByID, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const organizationCreate = `-- name: OrganizationCreate :one
INSERT INTO organizations (id, name, slug)
VALUES ($1, $2, $3)
RETURNING id, name, slug, created_at, updated_at
`

type OrganizationCreateParams struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
	Slug string      `json:"slug"`
}

func (q *Queries) OrganizationCreate(ctx context.Context, arg OrganizationCreateParams) (Organization, error) {
	row := q.db.QueryRow(ctx, organizationCreate, arg.ID, arg.Name, arg.Slug)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const organizationMembershipByUserAndOrg = `-- name: OrganizationMembershipByUserAndOrg :one
SELECT id, organization_id, user_id, role, created_at FROM organization_memberships
WHERE user_id = $1 AND organization_id = $2
`

type OrganizationMembershipByUserAndOrgParams struct {
	UserID         pgtype.UUID `json:"user_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) OrganizationMembershipByUserAndOrg(ctx context.Context, arg OrganizationMembershipByUserAndOrgParams) (OrganizationMembership, error) {
	row := q.db.QueryRow(ctx, organizationMembershipByUserAndOrg, arg.UserID, arg.OrganizationID)
	var i OrganizationMembership
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const organizationMembershipCreate = `-- name: OrganizationMembershipCreate :one
INSERT INTO organization_memberships (id, organization_id, user_id, role)
VALUES ($1, $2, $3, $4)
RETURNING id, organization_id, user_id, role, created_at
`

type OrganizationMembershipCreateParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	UserID         pgtype.UUID `json:"user_id"`
	Role           string      `json:"role"`
}

func (q *Queries) OrganizationMembershipCreate(ctx context.Context, arg OrganizationMembershipCreateParams) (OrganizationMembership, error) {
	row := q.db.QueryRow(ctx, organizationMembershipCreate,
		arg.ID,
		arg.OrganizationID,
		arg.UserID,
		arg.Role,
	)
	var i OrganizationMembership
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const organizationMembershipUpsertOwner = `-- name: OrganizationMembershipUpsertOwner :exec
INSERT INTO organization_memberships (id, organization_id, user_id, role)
VALUES ($1, $2, $3, 'owner')
ON CONFLICT (organization_id, user_id) DO UPDATE SET role = EXCLUDED.role
`

type OrganizationMembershipUpsertOwnerParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	UserID         pgtype.UUID `json:"user_id"`
}

func (q *Queries) OrganizationMembershipUpsertOwner(ctx context.Context, arg OrganizationMembershipUpsertOwnerParams) error {
	_, err := q.db.Exec(ctx, organizationMembershipUpsertOwner, arg.ID, arg.OrganizationID, arg.UserID)
	return err
}

const organizationsForUser = `-- name: OrganizationsForUser :many
SELECT o.id, o.name, o.slug, o.created_at, o.updated_at FROM organizations o
INNER JOIN organization_memberships m ON m.organization_id = o.id
WHERE m.user_id = $1
ORDER BY o.name ASC
`

func (q *Queries) OrganizationsForUser(ctx context.Context, userID pgtype.UUID) ([]Organization, error) {
	rows, err := q.db.Query(ctx, organizationsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Organization{}
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const organizationsListAll = `-- name: OrganizationsListAll :many
SELECT id, name, slug, created_at, updated_at FROM organizations ORDER BY name ASC
`

func (q *Queries) OrganizationsListAll(ctx context.Context) ([]Organization, error) {
	rows, err := q.db.Query(ctx, organizationsListAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Organization{}
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectClearScaledToZero = `-- name: ProjectClearScaledToZero :exec
UPDATE projects SET scaled_to_zero = false, updated_at = NOW() WHERE id = $1
`

func (q *Queries) ProjectClearScaledToZero(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, projectClearScaledToZero, id)
	return err
}

const projectCreate = `-- name: ProjectCreate :one

INSERT INTO projects (id, org_id, name, github_repository, github_installation_id, github_webhook_secret, root_directory, dockerfile_path, desired_instance_count)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, org_id, name, github_repository, github_installation_id, github_webhook_secret, root_directory, dockerfile_path, desired_instance_count, last_request_at, scaled_to_zero, scale_to_zero_enabled, created_at, updated_at
`

type ProjectCreateParams struct {
	ID                   pgtype.UUID `json:"id"`
	OrgID                pgtype.UUID `json:"org_id"`
	Name                 string      `json:"name"`
	GithubRepository     string      `json:"github_repository"`
	GithubInstallationID int64       `json:"github_installation_id"`
	GithubWebhookSecret  string      `json:"github_webhook_secret"`
	RootDirectory        string      `json:"root_directory"`
	DockerfilePath       string      `json:"dockerfile_path"`
	DesiredInstanceCount int32       `json:"desired_instance_count"`
}

// Projects --
func (q *Queries) ProjectCreate(ctx context.Context, arg ProjectCreateParams) (Project, error) {
	row := q.db.QueryRow(ctx, projectCreate,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.GithubRepository,
		arg.GithubInstallationID,
		arg.GithubWebhookSecret,
		arg.RootDirectory,
		arg.DockerfilePath,
		arg.DesiredInstanceCount,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.GithubRepository,
		&i.GithubInstallationID,
		&i.GithubWebhookSecret,
		&i.RootDirectory,
		&i.DockerfilePath,
		&i.DesiredInstanceCount,
		&i.LastRequestAt,
		&i.ScaledToZero,
		&i.ScaleToZeroEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const projectDeleteByIDAndOrg = `-- name: ProjectDeleteByIDAndOrg :exec
DELETE FROM projects WHERE id = $1 AND org_id = $2
`

type ProjectDeleteByIDAndOrgParams struct {
	ID    pgtype.UUID `json:"id"`
	OrgID pgtype.UUID `json:"org_id"`
}

func (q *Queries) ProjectDeleteByIDAndOrg(ctx context.Context, arg ProjectDeleteByIDAndOrgParams) error {
	_, err := q.db.Exec(ctx, projectDeleteByIDAndOrg, arg.ID, arg.OrgID)
	return err
}

const projectFindAllByOrgID = `-- name: ProjectFindAllByOrgID :many
SELECT id, org_id, name, github_repository, github_installation_id, github_webhook_secret, root_directory, dockerfile_path, desired_instance_count, last_request_at, scaled_to_zero, scale_to_zero_enabled, created_at, updated_at FROM projects WHERE org_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ProjectFindAllByOrgID(ctx context.Context, orgID pgtype.UUID) ([]Project, error) {
	rows, err := q.db.Query(ctx, projectFindAllByOrgID, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.GithubRepository,
			&i.GithubInstallationID,
			&i.GithubWebhookSecret,
			&i.RootDirectory,
			&i.DockerfilePath,
			&i.DesiredInstanceCount,
			&i.LastRequestAt,
			&i.ScaledToZero,
			&i.ScaleToZeroEnabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectFindByGitHubRepo = `-- name: ProjectFindByGitHubRepo :one
SELECT id, org_id, name, github_repository, github_installation_id, github_webhook_secret, root_directory, dockerfile_path, desired_instance_count, last_request_at, scaled_to_zero, scale_to_zero_enabled, created_at, updated_at FROM projects WHERE github_repository = $1
`

func (q *Queries) ProjectFindByGitHubRepo(ctx context.Context, githubRepository string) (Project, error) {
	row := q.db.QueryRow(ctx, projectFindByGitHubRepo, githubRepository)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.GithubRepository,
		&i.GithubInstallationID,
		&i.GithubWebhookSecret,
		&i.RootDirectory,
		&i.DockerfilePath,
		&i.DesiredInstanceCount,
		&i.LastRequestAt,
		&i.ScaledToZero,
		&i.ScaleToZeroEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const projectFirstByID = `-- name: ProjectFirstByID :one
SELECT id, org_id, name, github_repository, github_installation_id, github_webhook_secret, root_directory, dockerfile_path, desired_instance_count, last_request_at, scaled_to_zero, scale_to_zero_enabled, created_at, updated_at FROM projects WHERE id = $1
`

func (q *Queries) ProjectFirstByID(ctx context.Context, id pgtype.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, projectFirstByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.GithubRepository,
		&i.GithubInstallationID,
		&i.GithubWebhookSecret,
		&i.RootDirectory,
		&i.DockerfilePath,
		&i.DesiredInstanceCount,
		&i.LastRequestAt,
		&i.ScaledToZero,
		&i.ScaleToZeroEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const projectFirstByIDAndOrg = `-- name: ProjectFirstByIDAndOrg :one
SELECT id, org_id, name, github_repository, github_installation_id, github_webhook_secret, root_directory, dockerfile_path, desired_instance_count, last_request_at, scaled_to_zero, scale_to_zero_enabled, created_at, updated_at FROM projects WHERE id = $1 AND org_id = $2
`

type ProjectFirstByIDAndOrgParams struct {
	ID    pgtype.UUID `json:"id"`
	OrgID pgtype.UUID `json:"org_id"`
}

func (q *Queries) ProjectFirstByIDAndOrg(ctx context.Context, arg ProjectFirstByIDAndOrgParams) (Project, error) {
	row := q.db.QueryRow(ctx, projectFirstByIDAndOrg, arg.ID, arg.OrgID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.GithubRepository,
		&i.GithubInstallationID,
		&i.GithubWebhookSecret,
		&i.RootDirectory,
		&i.DockerfilePath,
		&i.DesiredInstanceCount,
		&i.LastRequestAt,
		&i.ScaledToZero,
		&i.ScaleToZeroEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const projectHTTPUsageRollupIncrement = `-- name: ProjectHTTPUsageRollupIncrement :exec
INSERT INTO project_http_usage_rollups (
    id, server_id, project_id, deployment_id, bucket_start,
    request_count, status_2xx, status_4xx, status_5xx, bytes_in, bytes_out, updated_at
) VALUES (
    gen_random_uuid(), $1, $2, $3, $4,
    $5, $6, $7, $8, $9, $10, NOW()
)
ON CONFLICT (server_id, project_id, deployment_id, bucket_start)
DO UPDATE SET
    request_count = project_http_usage_rollups.request_count + EXCLUDED.request_count,
    status_2xx = project_http_usage_rollups.status_2xx + EXCLUDED.status_2xx,
    status_4xx = project_http_usage_rollups.status_4xx + EXCLUDED.status_4xx,
    status_5xx = project_http_usage_rollups.status_5xx + EXCLUDED.status_5xx,
    bytes_in = project_http_usage_rollups.bytes_in + EXCLUDED.bytes_in,
    bytes_out = project_http_usage_rollups.bytes_out + EXCLUDED.bytes_out,
    updated_at = NOW()
`

type ProjectHTTPUsageRollupIncrementParams struct {
	ServerID     pgtype.UUID        `json:"server_id"`
	ProjectID    pgtype.UUID        `json:"project_id"`
	DeploymentID pgtype.UUID        `json:"deployment_id"`
	BucketStart  pgtype.Timestamptz `json:"bucket_start"`
	RequestCount int64              `json:"request_count"`
	Status2xx    int64              `json:"status_2xx"`
	Status4xx    int64              `json:"status_4xx"`
	Status5xx    int64              `json:"status_5xx"`
	BytesIn      int64              `json:"bytes_in"`
	BytesOut     int64              `json:"bytes_out"`
}

func (q *Queries) ProjectHTTPUsageRollupIncrement(ctx context.Context, arg ProjectHTTPUsageRollupIncrementParams) error {
	_, err := q.db.Exec(ctx, projectHTTPUsageRollupIncrement,
		arg.ServerID,
		arg.ProjectID,
		arg.DeploymentID,
		arg.BucketStart,
		arg.RequestCount,
		arg.Status2xx,
		arg.Status4xx,
		arg.Status5xx,
		arg.BytesIn,
		arg.BytesOut,
	)
	return err
}

const projectHTTPUsageRollupsAggregated = `-- name: ProjectHTTPUsageRollupsAggregated :many
SELECT
    bucket_start,
    COALESCE(SUM(request_count), 0)::bigint AS request_count,
    COALESCE(SUM(status_2xx), 0)::bigint AS status_2xx,
    COALESCE(SUM(status_4xx), 0)::bigint AS status_4xx,
    COALESCE(SUM(status_5xx), 0)::bigint AS status_5xx,
    COALESCE(SUM(bytes_in), 0)::bigint AS bytes_in,
    COALESCE(SUM(bytes_out), 0)::bigint AS bytes_out
FROM project_http_usage_rollups
WHERE project_id = $1
  AND bucket_start >= $2
  AND bucket_start <= $3
GROUP BY bucket_start
ORDER BY bucket_start ASC
`

type ProjectHTTPUsageRollupsAggregatedParams struct {
	ProjectID     pgtype.UUID        `json:"project_id"`
	BucketStart   pgtype.Timestamptz `json:"bucket_start"`
	BucketStart_2 pgtype.Timestamptz `json:"bucket_start_2"`
}

type ProjectHTTPUsageRollupsAggregatedRow struct {
	BucketStart  pgtype.Timestamptz `json:"bucket_start"`
	RequestCount int64              `json:"request_count"`
	Status2xx    int64              `json:"status_2xx"`
	Status4xx    int64              `json:"status_4xx"`
	Status5xx    int64              `json:"status_5xx"`
	BytesIn      int64              `json:"bytes_in"`
	BytesOut     int64              `json:"bytes_out"`
}

func (q *Queries) ProjectHTTPUsageRollupsAggregated(ctx context.Context, arg ProjectHTTPUsageRollupsAggregatedParams) ([]ProjectHTTPUsageRollupsAggregatedRow, error) {
	rows, err := q.db.Query(ctx, projectHTTPUsageRollupsAggregated, arg.ProjectID, arg.BucketStart, arg.BucketStart_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectHTTPUsageRollupsAggregatedRow{}
	for rows.Next() {
		var i ProjectHTTPUsageRollupsAggregatedRow
		if err := rows.Scan(
			&i.BucketStart,
			&i.RequestCount,
			&i.Status2xx,
			&i.Status4xx,
			&i.Status5xx,
			&i.BytesIn,
			&i.BytesOut,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectMarkScaledToZero = `-- name: ProjectMarkScaledToZero :exec
UPDATE projects
SET scaled_to_zero = true, updated_at = NOW()
WHERE id = $1
  AND scale_to_zero_enabled = true
  AND desired_instance_count > 0
  AND scaled_to_zero = false
`

func (q *Queries) ProjectMarkScaledToZero(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, projectMarkScaledToZero, id)
	return err
}

const projectUpdateDesiredInstanceCount = `-- name: ProjectUpdateDesiredInstanceCount :one
UPDATE projects
SET desired_instance_count = $2, updated_at = NOW()
WHERE id = $1 AND org_id = $3
RETURNING id, org_id, name, github_repository, github_installation_id, github_webhook_secret, root_directory, dockerfile_path, desired_instance_count, last_request_at, scaled_to_zero, scale_to_zero_enabled, created_at, updated_at
`

type ProjectUpdateDesiredInstanceCountParams struct {
	ID                   pgtype.UUID `json:"id"`
	DesiredInstanceCount int32       `json:"desired_instance_count"`
	OrgID                pgtype.UUID `json:"org_id"`
}

func (q *Queries) ProjectUpdateDesiredInstanceCount(ctx context.Context, arg ProjectUpdateDesiredInstanceCountParams) (Project, error) {
	row := q.db.QueryRow(ctx, projectUpdateDesiredInstanceCount, arg.ID, arg.DesiredInstanceCount, arg.OrgID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.GithubRepository,
		&i.GithubInstallationID,
		&i.GithubWebhookSecret,
		&i.RootDirectory,
		&i.DockerfilePath,
		&i.DesiredInstanceCount,
		&i.LastRequestAt,
		&i.ScaledToZero,
		&i.ScaleToZeroEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const projectUpdateLastRequestAt = `-- name: ProjectUpdateLastRequestAt :exec
UPDATE projects SET last_request_at = NOW(), updated_at = NOW() WHERE id = $1
`

func (q *Queries) ProjectUpdateLastRequestAt(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, projectUpdateLastRequestAt, id)
	return err
}

const projectUpdateScaleToZeroEnabled = `-- name: ProjectUpdateScaleToZeroEnabled :one
UPDATE projects
SET scale_to_zero_enabled = $2, updated_at = NOW()
WHERE id = $1 AND org_id = $3
RETURNING id, org_id, name, github_repository, github_installation_id, github_webhook_secret, root_directory, dockerfile_path, desired_instance_count, last_request_at, scaled_to_zero, scale_to_zero_enabled, created_at, updated_at
`

type ProjectUpdateScaleToZeroEnabledParams struct {
	ID                 pgtype.UUID `json:"id"`
	ScaleToZeroEnabled bool        `json:"scale_to_zero_enabled"`
	OrgID              pgtype.UUID `json:"org_id"`
}

func (q *Queries) ProjectUpdateScaleToZeroEnabled(ctx context.Context, arg ProjectUpdateScaleToZeroEnabledParams) (Project, error) {
	row := q.db.QueryRow(ctx, projectUpdateScaleToZeroEnabled, arg.ID, arg.ScaleToZeroEnabled, arg.OrgID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.GithubRepository,
		&i.GithubInstallationID,
		&i.GithubWebhookSecret,
		&i.RootDirectory,
		&i.DockerfilePath,
		&i.DesiredInstanceCount,
		&i.LastRequestAt,
		&i.ScaledToZero,
		&i.ScaleToZeroEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const projectUpdateWebhookSecret = `-- name: ProjectUpdateWebhookSecret :one
UPDATE projects
SET github_webhook_secret = $2, updated_at = NOW()
WHERE id = $1 AND org_id = $3
RETURNING id, org_id, name, github_repository, github_installation_id, github_webhook_secret, root_directory, dockerfile_path, desired_instance_count, last_request_at, scaled_to_zero, scale_to_zero_enabled, created_at, updated_at
`

type ProjectUpdateWebhookSecretParams struct {
	ID                  pgtype.UUID `json:"id"`
	GithubWebhookSecret string      `json:"github_webhook_secret"`
	OrgID               pgtype.UUID `json:"org_id"`
}

func (q *Queries) ProjectUpdateWebhookSecret(ctx context.Context, arg ProjectUpdateWebhookSecretParams) (Project, error) {
	row := q.db.QueryRow(ctx, projectUpdateWebhookSecret, arg.ID, arg.GithubWebhookSecret, arg.OrgID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.GithubRepository,
		&i.GithubInstallationID,
		&i.GithubWebhookSecret,
		&i.RootDirectory,
		&i.DockerfilePath,
		&i.DesiredInstanceCount,
		&i.LastRequestAt,
		&i.ScaledToZero,
		&i.ScaleToZeroEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const projectsFindForIdleScaleDown = `-- name: ProjectsFindForIdleScaleDown :many
SELECT id, org_id, name, github_repository, github_installation_id, github_webhook_secret, root_directory, dockerfile_path, desired_instance_count, last_request_at, scaled_to_zero, scale_to_zero_enabled, created_at, updated_at FROM projects
WHERE scale_to_zero_enabled = true
  AND desired_instance_count > 0
  AND scaled_to_zero = false
  AND last_request_at IS NOT NULL
  AND last_request_at < NOW() - ($1::bigint * INTERVAL '1 second')
ORDER BY last_request_at ASC
LIMIT 100
`

func (q *Queries) ProjectsFindForIdleScaleDown(ctx context.Context, dollar_1 int64) ([]Project, error) {
	rows, err := q.db.Query(ctx, projectsFindForIdleScaleDown, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.GithubRepository,
			&i.GithubInstallationID,
			&i.GithubWebhookSecret,
			&i.RootDirectory,
			&i.DockerfilePath,
			&i.DesiredInstanceCount,
			&i.LastRequestAt,
			&i.ScaledToZero,
			&i.ScaleToZeroEnabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const routeFindActive = `-- name: RouteFindActive :many
SELECT d.domain_name,
       d.project_id,
       d.deployment_id,
       d.redirect_to,
       d.redirect_status_code,
       v.ip_address AS vm_ip,
       v.port AS vm_port,
       v.server_id,
       v.id AS vm_id
FROM domains d
LEFT JOIN deployments dep ON d.deployment_id = dep.id
LEFT JOIN deployment_instances di ON di.deployment_id = dep.id
    AND di.deleted_at IS NULL
    AND di.status = 'running'
LEFT JOIN vms v ON di.vm_id = v.id AND v.deleted_at IS NULL
WHERE d.verified_at IS NOT NULL
`

type RouteFindActiveRow struct {
	DomainName         string      `json:"domain_name"`
	ProjectID          pgtype.UUID `json:"project_id"`
	DeploymentID       pgtype.UUID `json:"deployment_id"`
	RedirectTo         pgtype.Text `json:"redirect_to"`
	RedirectStatusCode pgtype.Int4 `json:"redirect_status_code"`
	VmIp               *netip.Addr `json:"vm_ip"`
	VmPort             pgtype.Int4 `json:"vm_port"`
	ServerID           pgtype.UUID `json:"server_id"`
	VmID               pgtype.UUID `json:"vm_id"`
}

func (q *Queries) RouteFindActive(ctx context.Context) ([]RouteFindActiveRow, error) {
	rows, err := q.db.Query(ctx, routeFindActive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RouteFindActiveRow{}
	for rows.Next() {
		var i RouteFindActiveRow
		if err := rows.Scan(
			&i.DomainName,
			&i.ProjectID,
			&i.DeploymentID,
			&i.RedirectTo,
			&i.RedirectStatusCode,
			&i.VmIp,
			&i.VmPort,
			&i.ServerID,
			&i.VmID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const serverAllocateIPRange = `-- name: ServerAllocateIPRange :one
SELECT CASE
    WHEN MAX(ip_range) IS NULL THEN '10.0.0.0/20'::CIDR
    ELSE (MAX(ip_range) + 1)::CIDR
END AS ip_range
FROM servers
`

func (q *Queries) ServerAllocateIPRange(ctx context.Context) (netip.Prefix, error) {
	row := q.db.QueryRow(ctx, serverAllocateIPRange)
	var ip_range netip.Prefix
	err := row.Scan(&ip_range)
	return ip_range, err
}

const serverFindAll = `-- name: ServerFindAll :many
SELECT id, hostname, internal_ip, ip_range, status, last_heartbeat_at, created_at, updated_at FROM servers ORDER BY created_at
`

func (q *Queries) ServerFindAll(ctx context.Context) ([]Server, error) {
	rows, err := q.db.Query(ctx, serverFindAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Server{}
	for rows.Next() {
		var i Server
		if err := rows.Scan(
			&i.ID,
			&i.Hostname,
			&i.InternalIp,
			&i.IpRange,
			&i.Status,
			&i.LastHeartbeatAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const serverFindByID = `-- name: ServerFindByID :one
SELECT id, hostname, internal_ip, ip_range, status, last_heartbeat_at, created_at, updated_at FROM servers WHERE id = $1
`

func (q *Queries) ServerFindByID(ctx context.Context, id pgtype.UUID) (Server, error) {
	row := q.db.QueryRow(ctx, serverFindByID, id)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.Hostname,
		&i.InternalIp,
		&i.IpRange,
		&i.Status,
		&i.LastHeartbeatAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const serverFindDead = `-- name: ServerFindDead :many
SELECT id, hostname, internal_ip, ip_range, status, last_heartbeat_at, created_at, updated_at FROM servers
WHERE status = 'active'
  AND last_heartbeat_at < NOW() - INTERVAL '30 seconds'
`

func (q *Queries) ServerFindDead(ctx context.Context) ([]Server, error) {
	rows, err := q.db.Query(ctx, serverFindDead)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Server{}
	for rows.Next() {
		var i Server
		if err := rows.Scan(
			&i.ID,
			&i.Hostname,
			&i.InternalIp,
			&i.IpRange,
			&i.Status,
			&i.LastHeartbeatAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const serverFindLeastLoaded = `-- name: ServerFindLeastLoaded :one
SELECT s.id, s.hostname, s.internal_ip, s.ip_range, s.status, s.last_heartbeat_at, s.created_at, s.updated_at FROM servers s
LEFT JOIN vms v ON v.server_id = s.id AND v.deleted_at IS NULL
WHERE s.status = 'active'
  AND s.last_heartbeat_at > NOW() - INTERVAL '3 minutes'
GROUP BY s.id
ORDER BY COUNT(v.id) ASC, s.last_heartbeat_at DESC
LIMIT 1
`

func (q *Queries) ServerFindLeastLoaded(ctx context.Context) (Server, error) {
	row := q.db.QueryRow(ctx, serverFindLeastLoaded)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.Hostname,
		&i.InternalIp,
		&i.IpRange,
		&i.Status,
		&i.LastHeartbeatAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const serverHeartbeat = `-- name: ServerHeartbeat :exec
UPDATE servers SET last_heartbeat_at = NOW(), updated_at = NOW() WHERE id = $1
`

func (q *Queries) ServerHeartbeat(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, serverHeartbeat, id)
	return err
}

const serverRegister = `-- name: ServerRegister :one
INSERT INTO servers (id, hostname, internal_ip, ip_range, status, last_heartbeat_at)
VALUES ($1, $2, $3, $4, 'active', NOW())
ON CONFLICT (id) DO UPDATE SET
    hostname = EXCLUDED.hostname,
    internal_ip = EXCLUDED.internal_ip,
    status = 'active',
    last_heartbeat_at = NOW(),
    updated_at = NOW()
RETURNING id, hostname, internal_ip, ip_range, status, last_heartbeat_at, created_at, updated_at
`

type ServerRegisterParams struct {
	ID         pgtype.UUID  `json:"id"`
	Hostname   string       `json:"hostname"`
	InternalIp string       `json:"internal_ip"`
	IpRange    netip.Prefix `json:"ip_range"`
}

func (q *Queries) ServerRegister(ctx context.Context, arg ServerRegisterParams) (Server, error) {
	row := q.db.QueryRow(ctx, serverRegister,
		arg.ID,
		arg.Hostname,
		arg.InternalIp,
		arg.IpRange,
	)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.Hostname,
		&i.InternalIp,
		&i.IpRange,
		&i.Status,
		&i.LastHeartbeatAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const serverSetDrained = `-- name: ServerSetDrained :exec
UPDATE servers SET status = 'drained', updated_at = NOW() WHERE id = $1
`

func (q *Queries) ServerSetDrained(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, serverSetDrained, id)
	return err
}

const serverSettingEnsure = `-- name: ServerSettingEnsure :exec
INSERT INTO server_settings (server_id) VALUES ($1) ON CONFLICT (server_id) DO NOTHING
`

func (q *Queries) ServerSettingEnsure(ctx context.Context, serverID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, serverSettingEnsure, serverID)
	return err
}

const serverSettingGet = `-- name: ServerSettingGet :one
SELECT server_id, runtime_override, advertise_host, cloud_hypervisor_bin, cloud_hypervisor_kernel_path, cloud_hypervisor_initramfs_path, updated_at FROM server_settings WHERE server_id = $1
`

func (q *Queries) ServerSettingGet(ctx context.Context, serverID pgtype.UUID) (ServerSetting, error) {
	row := q.db.QueryRow(ctx, serverSettingGet, serverID)
	var i ServerSetting
	err := row.Scan(
		&i.ServerID,
		&i.RuntimeOverride,
		&i.AdvertiseHost,
		&i.CloudHypervisorBin,
		&i.CloudHypervisorKernelPath,
		&i.CloudHypervisorInitramfsPath,
		&i.UpdatedAt,
	)
	return i, err
}

const serverSettingSeedAdvertiseHostIfUnset = `-- name: ServerSettingSeedAdvertiseHostIfUnset :exec
UPDATE server_settings
SET advertise_host = $2, updated_at = NOW()
WHERE server_id = $1
  AND (advertise_host = '' OR BTRIM(advertise_host) = '')
`

type ServerSettingSeedAdvertiseHostIfUnsetParams struct {
	ServerID      pgtype.UUID `json:"server_id"`
	AdvertiseHost string      `json:"advertise_host"`
}

func (q *Queries) ServerSettingSeedAdvertiseHostIfUnset(ctx context.Context, arg ServerSettingSeedAdvertiseHostIfUnsetParams) error {
	_, err := q.db.Exec(ctx, serverSettingSeedAdvertiseHostIfUnset, arg.ServerID, arg.AdvertiseHost)
	return err
}

const serverUpdateStatus = `-- name: ServerUpdateStatus :exec
UPDATE servers SET status = $2, updated_at = NOW() WHERE id = $1
`

type ServerUpdateStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) ServerUpdateStatus(ctx context.Context, arg ServerUpdateStatusParams) error {
	_, err := q.db.Exec(ctx, serverUpdateStatus, arg.ID, arg.Status)
	return err
}

const trySessionAdvisoryLock = `-- name: TrySessionAdvisoryLock :one
SELECT pg_try_advisory_lock(hashtext($1))
`

func (q *Queries) TrySessionAdvisoryLock(ctx context.Context, hashtext string) (bool, error) {
	row := q.db.QueryRow(ctx, trySessionAdvisoryLock, hashtext)
	var pg_try_advisory_lock bool
	err := row.Scan(&pg_try_advisory_lock)
	return pg_try_advisory_lock, err
}

const userByEmail = `-- name: UserByEmail :one
SELECT id, email, password_hash, display_name, created_at, updated_at FROM users WHERE LOWER(email) = LOWER($1)
`

func (q *Queries) UserByEmail(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRow(ctx, userByEmail, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const userByID = `-- name: UserByID :one
SELECT id, email, password_hash, display_name, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) UserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, userByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const userCount = `-- name: UserCount :one

SELECT COUNT(*)::bigint FROM users
`

// Auth & organizations --
func (q *Queries) UserCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, userCount)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const userCreate = `-- name: UserCreate :one
INSERT INTO users (id, email, password_hash, display_name)
VALUES ($1, $2, $3, $4)
RETURNING id, email, password_hash, display_name, created_at, updated_at
`

type UserCreateParams struct {
	ID           pgtype.UUID `json:"id"`
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	DisplayName  string      `json:"display_name"`
}

func (q *Queries) UserCreate(ctx context.Context, arg UserCreateParams) (User, error) {
	row := q.db.QueryRow(ctx, userCreate,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.DisplayName,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const userSessionByTokenHash = `-- name: UserSessionByTokenHash :one
SELECT id, user_id, token_hash, current_organization_id, expires_at, created_at FROM user_sessions
WHERE token_hash = $1 AND expires_at > NOW()
`

func (q *Queries) UserSessionByTokenHash(ctx context.Context, tokenHash []byte) (UserSession, error) {
	row := q.db.QueryRow(ctx, userSessionByTokenHash, tokenHash)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CurrentOrganizationID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const userSessionCreate = `-- name: UserSessionCreate :one
INSERT INTO user_sessions (id, user_id, token_hash, current_organization_id, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, token_hash, current_organization_id, expires_at, created_at
`

type UserSessionCreateParams struct {
	ID                    pgtype.UUID        `json:"id"`
	UserID                pgtype.UUID        `json:"user_id"`
	TokenHash             []byte             `json:"token_hash"`
	CurrentOrganizationID pgtype.UUID        `json:"current_organization_id"`
	ExpiresAt             pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) UserSessionCreate(ctx context.Context, arg UserSessionCreateParams) (UserSession, error) {
	row := q.db.QueryRow(ctx, userSessionCreate,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.CurrentOrganizationID,
		arg.ExpiresAt,
	)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CurrentOrganizationID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const userSessionDelete = `-- name: UserSessionDelete :exec
DELETE FROM user_sessions WHERE id = $1
`

func (q *Queries) UserSessionDelete(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, userSessionDelete, id)
	return err
}

const userSessionDeleteAllForUser = `-- name: UserSessionDeleteAllForUser :exec
DELETE FROM user_sessions WHERE user_id = $1
`

func (q *Queries) UserSessionDeleteAllForUser(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, userSessionDeleteAllForUser, userID)
	return err
}

const userSessionUpdateCurrentOrg = `-- name: UserSessionUpdateCurrentOrg :one
UPDATE user_sessions
SET current_organization_id = $2
WHERE id = $1
RETURNING id, user_id, token_hash, current_organization_id, expires_at, created_at
`

type UserSessionUpdateCurrentOrgParams struct {
	ID                    pgtype.UUID `json:"id"`
	CurrentOrganizationID pgtype.UUID `json:"current_organization_id"`
}

func (q *Queries) UserSessionUpdateCurrentOrg(ctx context.Context, arg UserSessionUpdateCurrentOrgParams) (UserSession, error) {
	row := q.db.QueryRow(ctx, userSessionUpdateCurrentOrg, arg.ID, arg.CurrentOrganizationID)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CurrentOrganizationID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const userUpdateDisplayName = `-- name: UserUpdateDisplayName :exec
UPDATE users SET display_name = $2, updated_at = NOW() WHERE id = $1
`

type UserUpdateDisplayNameParams struct {
	ID          pgtype.UUID `json:"id"`
	DisplayName string      `json:"display_name"`
}

func (q *Queries) UserUpdateDisplayName(ctx context.Context, arg UserUpdateDisplayNameParams) error {
	_, err := q.db.Exec(ctx, userUpdateDisplayName, arg.ID, arg.DisplayName)
	return err
}

const userUpdatePasswordHash = `-- name: UserUpdatePasswordHash :exec
UPDATE users SET password_hash = $2, updated_at = NOW() WHERE id = $1
`

type UserUpdatePasswordHashParams struct {
	ID           pgtype.UUID `json:"id"`
	PasswordHash string      `json:"password_hash"`
}

func (q *Queries) UserUpdatePasswordHash(ctx context.Context, arg UserUpdatePasswordHashParams) error {
	_, err := q.db.Exec(ctx, userUpdatePasswordHash, arg.ID, arg.PasswordHash)
	return err
}

const vMCreate = `-- name: VMCreate :one

INSERT INTO vms (id, server_id, image_id, status, vcpus, memory, ip_address, port, env_variables)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, server_id, image_id, status, vcpus, memory, ip_address, port, env_variables, deleted_at, created_at, updated_at
`

type VMCreateParams struct {
	ID           pgtype.UUID `json:"id"`
	ServerID     pgtype.UUID `json:"server_id"`
	ImageID      pgtype.UUID `json:"image_id"`
	Status       string      `json:"status"`
	Vcpus        int32       `json:"vcpus"`
	Memory       int32       `json:"memory"`
	IpAddress    netip.Addr  `json:"ip_address"`
	Port         pgtype.Int4 `json:"port"`
	EnvVariables pgtype.Text `json:"env_variables"`
}

// VMs --
func (q *Queries) VMCreate(ctx context.Context, arg VMCreateParams) (Vm, error) {
	row := q.db.QueryRow(ctx, vMCreate,
		arg.ID,
		arg.ServerID,
		arg.ImageID,
		arg.Status,
		arg.Vcpus,
		arg.Memory,
		arg.IpAddress,
		arg.Port,
		arg.EnvVariables,
	)
	var i Vm
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.ImageID,
		&i.Status,
		&i.Vcpus,
		&i.Memory,
		&i.IpAddress,
		&i.Port,
		&i.EnvVariables,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const vMFindByServerID = `-- name: VMFindByServerID :many
SELECT id, server_id, image_id, status, vcpus, memory, ip_address, port, env_variables, deleted_at, created_at, updated_at FROM vms WHERE server_id = $1 AND deleted_at IS NULL
`

func (q *Queries) VMFindByServerID(ctx context.Context, serverID pgtype.UUID) ([]Vm, error) {
	rows, err := q.db.Query(ctx, vMFindByServerID, serverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Vm{}
	for rows.Next() {
		var i Vm
		if err := rows.Scan(
			&i.ID,
			&i.ServerID,
			&i.ImageID,
			&i.Status,
			&i.Vcpus,
			&i.Memory,
			&i.IpAddress,
			&i.Port,
			&i.EnvVariables,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const vMFirstByID = `-- name: VMFirstByID :one
SELECT id, server_id, image_id, status, vcpus, memory, ip_address, port, env_variables, deleted_at, created_at, updated_at FROM vms WHERE id = $1
`

func (q *Queries) VMFirstByID(ctx context.Context, id pgtype.UUID) (Vm, error) {
	row := q.db.QueryRow(ctx, vMFirstByID, id)
	var i Vm
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.ImageID,
		&i.Status,
		&i.Vcpus,
		&i.Memory,
		&i.IpAddress,
		&i.Port,
		&i.EnvVariables,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const vMLogCreate = `-- name: VMLogCreate :exec

INSERT INTO vm_logs (id, vm_id, message, level)
VALUES ($1, $2, $3, $4)
`

type VMLogCreateParams struct {
	ID      pgtype.UUID `json:"id"`
	VmID    pgtype.UUID `json:"vm_id"`
	Message string      `json:"message"`
	Level   string      `json:"level"`
}

// VM Logs --
func (q *Queries) VMLogCreate(ctx context.Context, arg VMLogCreateParams) error {
	_, err := q.db.Exec(ctx, vMLogCreate,
		arg.ID,
		arg.VmID,
		arg.Message,
		arg.Level,
	)
	return err
}

const vMLogsByVMID = `-- name: VMLogsByVMID :many
SELECT id, vm_id, message, level, created_at FROM vm_logs WHERE vm_id = $1 ORDER BY created_at
`

func (q *Queries) VMLogsByVMID(ctx context.Context, vmID pgtype.UUID) ([]VmLog, error) {
	rows, err := q.db.Query(ctx, vMLogsByVMID, vmID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VmLog{}
	for rows.Next() {
		var i VmLog
		if err := rows.Scan(
			&i.ID,
			&i.VmID,
			&i.Message,
			&i.Level,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const vMNextIPAddress = `-- name: VMNextIPAddress :one
SELECT (CASE
    WHEN MAX(ip_address) IS NULL THEN (host(network($1::CIDR))::INET + 1)
    ELSE (MAX(ip_address) + 2)
END)::INET AS ip_address
FROM vms
WHERE server_id = $2
`

type VMNextIPAddressParams struct {
	IpRange  netip.Prefix `json:"ip_range"`
	ServerID pgtype.UUID  `json:"server_id"`
}

func (q *Queries) VMNextIPAddress(ctx context.Context, arg VMNextIPAddressParams) (netip.Addr, error) {
	row := q.db.QueryRow(ctx, vMNextIPAddress, arg.IpRange, arg.ServerID)
	var ip_address netip.Addr
	err := row.Scan(&ip_address)
	return ip_address, err
}

const vMSoftDelete = `-- name: VMSoftDelete :exec
UPDATE vms SET deleted_at = NOW(), updated_at = NOW() WHERE id = $1
`

func (q *Queries) VMSoftDelete(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, vMSoftDelete, id)
	return err
}

const vMUpdateStatus = `-- name: VMUpdateStatus :one
UPDATE vms SET status = $2, updated_at = NOW() WHERE id = $1 RETURNING id, server_id, image_id, status, vcpus, memory, ip_address, port, env_variables, deleted_at, created_at, updated_at
`

type VMUpdateStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) VMUpdateStatus(ctx context.Context, arg VMUpdateStatusParams) (Vm, error) {
	row := q.db.QueryRow(ctx, vMUpdateStatus, arg.ID, arg.Status)
	var i Vm
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.ImageID,
		&i.Status,
		&i.Vcpus,
		&i.Memory,
		&i.IpAddress,
		&i.Port,
		&i.EnvVariables,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
